fn main() {
    ensure_ned_sidecar_placeholder();
    tauri_build::build()
}

fn ensure_ned_sidecar_placeholder() {
    let target = std::env::var("TARGET").unwrap_or_else(|_| std::env::consts::ARCH.to_string());
    let extension = if target.contains("windows") {
        ".exe"
    } else {
        ""
    };
    let path = std::path::Path::new("binaries").join(format!("ned-{target}{extension}"));
    if path.exists() {
        return;
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("create sidecar directory");
    }
    std::fs::write(
        &path,
        b"placeholder generated by build.rs; run pnpm run prepare:sidecars for release packaging\n",
    )
    .expect("write ned sidecar placeholder");
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut permissions = std::fs::metadata(&path)
            .expect("ned sidecar placeholder metadata")
            .permissions();
        permissions.set_mode(0o755);
        std::fs::set_permissions(&path, permissions)
            .expect("make ned sidecar placeholder executable");
    }
}
