use crate::{
    document_ast::{export_body_text_from_ast, AstSourceRange, DocumentBlock},
    escape_css, escape_html, escape_pdf, escape_xml, metadata_string, render_export_template,
    CompileResponse, ExportManifest,
};
use chrono::Utc;
use serde_json::Value;
use std::{
    fs,
    io::{Cursor, Write},
    path::{Path, PathBuf},
};
use zip::{write::SimpleFileOptions, CompressionMethod, ZipWriter};

#[derive(Debug)]
struct ExportMedia {
    source: String,
    source_file: Option<String>,
    relationship_id: String,
    path: String,
    extension: String,
    content_type: String,
    bytes: Vec<u8>,
}

pub(crate) fn render_full_html(response: &CompileResponse, options: &Value) -> String {
    let brand_color = options
        .get("brandColor")
        .and_then(Value::as_str)
        .or_else(|| {
            response
                .metadata
                .pointer("/brand/color")
                .and_then(Value::as_str)
        })
        .unwrap_or("#275DA8");
    let watermark = options
        .get("watermark")
        .and_then(Value::as_str)
        .unwrap_or("");
    let brand_font = metadata_string(&response.metadata, "brand.font")
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| "Inter,Arial,sans-serif".to_string());
    let subtitle = metadata_string(&response.metadata, "subtitle");
    let author = metadata_string(&response.metadata, "author");
    let date = metadata_string(&response.metadata, "date");
    let version = metadata_string(&response.metadata, "version");
    let classification = metadata_string(&response.metadata, "classification");
    let brand = metadata_string(&response.metadata, "brand.name");
    let logo = export_logo(&response.metadata);
    let header_template = metadata_string(&response.metadata, "layout.header")
        .or_else(|| Some(response.semantic.title.clone()));
    let footer_template = metadata_string(&response.metadata, "layout.footer").or_else(|| {
        include_page_numbers(options).then(|| "Page {{page}} of {{pages}}".to_string())
    });
    let running_header = render_export_template(
        header_template.as_deref().unwrap_or(""),
        response,
        classification.as_deref().unwrap_or(""),
    );
    let running_footer = render_export_template(
        footer_template.as_deref().unwrap_or(""),
        response,
        classification.as_deref().unwrap_or(""),
    );
    let cover_meta = [author, date, version, classification, brand]
        .into_iter()
        .flatten()
        .map(|value| format!("<p>{}</p>", escape_html(&value)))
        .collect::<String>();
    let appendix_sections = html_appendix_sections(response, options);
    let style_tag = if include_styles(options) {
        format!(
            "<style>{}</style>",
            export_css(
                brand_color,
                watermark,
                &brand_font,
                include_page_numbers(options),
                layout_preset(options),
                include_syntax_highlighting(options),
                &response.metadata,
            )
        )
    } else {
        String::new()
    };
    let cover_section = if include_cover_page(options) {
        format!(
            "<section class=\"cover\">{}<h1>{}</h1>{}<p class=\"status\">{}</p>{}</section>",
            logo.as_ref()
                .map(|src| format!(
                    "<img class=\"cover-logo\" src=\"{}\" alt=\"{} logo\"/>",
                    escape_html(src),
                    escape_html(&response.semantic.title)
                ))
                .unwrap_or_default(),
            escape_html(&response.semantic.title),
            subtitle
                .map(|value| format!("<p class=\"subtitle\">{}</p>", escape_html(&value)))
                .unwrap_or_default(),
            escape_html(&response.semantic.status),
            cover_meta
        )
    } else {
        String::new()
    };
    let body_html = if include_syntax_highlighting(options) {
        highlight_code_blocks(&response.html)
    } else {
        response.html.clone()
    };
    format!(
        "<!doctype html><html><head><meta charset=\"utf-8\"><title>{}</title>{}</head><body><div class=\"running-header\">{}</div>{}<main>{}{}</main><footer><strong>{}</strong><span>{}</span><small>{}</small></footer></body></html>",
        escape_html(&response.semantic.title),
        style_tag,
        escape_html(&running_header),
        cover_section,
        body_html,
        appendix_sections,
        escape_html(&running_footer),
        escape_html("Generated by NEditor"),
        escape_html(&Utc::now().to_rfc3339())
    )
}

pub(crate) fn render_pdf_bytes(response: &CompileResponse, options: &Value) -> Vec<u8> {
    let pages = build_pdf_pages(response, options);
    let mut objects = vec![
        String::new(),
        String::new(),
        "3 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n".to_string(),
    ];
    let mut page_ids = Vec::new();

    for page_lines in pages {
        let page_id = objects.len() + 1;
        let content_id = page_id + 1;
        page_ids.push(page_id);
        let stream = page_lines
            .iter()
            .take(60)
            .enumerate()
            .map(|(index, line)| {
                format!(
                    "BT /F1 10 Tf 50 {} Td ({}) Tj ET\n",
                    780 - (index as i32 * 12),
                    escape_pdf(line)
                )
            })
            .collect::<String>();
        objects.push(format!(
            "{page_id} 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents {content_id} 0 R >> endobj\n"
        ));
        objects.push(format!(
            "{content_id} 0 obj << /Length {} >> stream\n{}endstream endobj\n",
            stream.len(),
            stream
        ));
    }

    let kids = page_ids
        .iter()
        .map(|id| format!("{id} 0 R"))
        .collect::<Vec<_>>()
        .join(" ");
    objects[0] = "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n".to_string();
    objects[1] = format!(
        "2 0 obj << /Type /Pages /Kids [{kids}] /Count {} >> endobj\n",
        page_ids.len()
    );

    let mut pdf = b"%PDF-1.4\n".to_vec();
    let mut offsets = Vec::new();
    for object in &objects {
        offsets.push(pdf.len());
        pdf.extend_from_slice(object.as_bytes());
    }
    let xref = pdf.len();
    pdf.extend_from_slice(
        format!("xref\n0 {}\n0000000000 65535 f \n", objects.len() + 1).as_bytes(),
    );
    for offset in offsets {
        pdf.extend_from_slice(format!("{offset:010} 00000 n \n").as_bytes());
    }
    pdf.extend_from_slice(
        format!(
            "trailer << /Size {} /Root 1 0 R >>\nstartxref\n{}\n%%EOF\n",
            objects.len() + 1,
            xref
        )
        .as_bytes(),
    );
    pdf
}

pub(crate) fn render_docx_bytes(
    response: &CompileResponse,
    options_value: &Value,
) -> Result<Vec<u8>, String> {
    let media = collect_docx_media(response);
    let mut cursor = Cursor::new(Vec::new());
    let mut zip = ZipWriter::new(&mut cursor);
    let options = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);
    zip.start_file("[Content_Types].xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_docx_content_types(&media).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.add_directory("_rels/", options)
        .map_err(|err| err.to_string())?;
    zip.start_file("_rels/.rels", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_root_relationships("word/document.xml").as_bytes())
        .map_err(|err| err.to_string())?;
    zip.add_directory("docProps/", options)
        .map_err(|err| err.to_string())?;
    zip.start_file("docProps/core.xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_core_properties(response).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.add_directory("word/", options)
        .map_err(|err| err.to_string())?;
    zip.add_directory("word/_rels/", options)
        .map_err(|err| err.to_string())?;
    zip.start_file("word/_rels/document.xml.rels", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_docx_document_relationships(&media).as_bytes())
        .map_err(|err| err.to_string())?;
    if !media.is_empty() {
        zip.add_directory("word/media/", options)
            .map_err(|err| err.to_string())?;
        for item in &media {
            zip.start_file(format!("word/{}", item.path), options)
                .map_err(|err| err.to_string())?;
            zip.write_all(&item.bytes).map_err(|err| err.to_string())?;
        }
    }
    zip.start_file("word/header1.xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_docx_header(response, options_value).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.start_file("word/footer1.xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_docx_footer(response, options_value).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.start_file("word/document.xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_docx_document(response, options_value, &media).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.finish().map_err(|err| err.to_string())?;
    Ok(cursor.into_inner())
}

pub(crate) fn render_pptx_bytes(
    response: &CompileResponse,
    options_value: &Value,
) -> Result<Vec<u8>, String> {
    let slides = build_pptx_slides(response, options_value);
    let media = collect_pptx_media(response);
    let mut cursor = Cursor::new(Vec::new());
    let mut zip = ZipWriter::new(&mut cursor);
    let options = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);
    zip.start_file("[Content_Types].xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_pptx_content_types(&slides, &media).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.add_directory("_rels/", options)
        .map_err(|err| err.to_string())?;
    zip.start_file("_rels/.rels", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_root_relationships("ppt/presentation.xml").as_bytes())
        .map_err(|err| err.to_string())?;
    zip.add_directory("docProps/", options)
        .map_err(|err| err.to_string())?;
    zip.start_file("docProps/core.xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_core_properties(response).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.add_directory("ppt/_rels/", options)
        .map_err(|err| err.to_string())?;
    zip.start_file("ppt/_rels/presentation.xml.rels", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_pptx_relationships(slides.len()).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.add_directory("ppt/slides/", options)
        .map_err(|err| err.to_string())?;
    let has_slide_relationships =
        !media.is_empty() || slides.iter().any(|slide| !slide.notes.is_empty());
    if has_slide_relationships {
        zip.add_directory("ppt/slides/_rels/", options)
            .map_err(|err| err.to_string())?;
    }
    if slides.iter().any(|slide| !slide.notes.is_empty()) {
        zip.add_directory("ppt/notesSlides/", options)
            .map_err(|err| err.to_string())?;
    }
    if !media.is_empty() {
        zip.add_directory("ppt/media/", options)
            .map_err(|err| err.to_string())?;
        for item in &media {
            zip.start_file(format!("ppt/{}", item.path), options)
                .map_err(|err| err.to_string())?;
            zip.write_all(&item.bytes).map_err(|err| err.to_string())?;
        }
    }
    zip.start_file("ppt/presentation.xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_pptx_presentation(slides.len()).as_bytes())
        .map_err(|err| err.to_string())?;
    for (index, slide) in slides.iter().enumerate() {
        let slide_media = pptx_slide_media(slide, &media);
        if !slide_media.is_empty() || !slide.notes.is_empty() {
            zip.start_file(
                format!("ppt/slides/_rels/slide{}.xml.rels", index + 1),
                options,
            )
            .map_err(|err| err.to_string())?;
            zip.write_all(
                render_pptx_slide_relationships(
                    &slide_media,
                    (!slide.notes.is_empty()).then_some(index + 1),
                )
                .as_bytes(),
            )
            .map_err(|err| err.to_string())?;
        }
        zip.start_file(format!("ppt/slides/slide{}.xml", index + 1), options)
            .map_err(|err| err.to_string())?;
        zip.write_all(render_pptx_slide(slide, &slide_media).as_bytes())
            .map_err(|err| err.to_string())?;
        if !slide.notes.is_empty() {
            zip.start_file(
                format!("ppt/notesSlides/notesSlide{}.xml", index + 1),
                options,
            )
            .map_err(|err| err.to_string())?;
            zip.write_all(render_pptx_notes_slide(slide).as_bytes())
                .map_err(|err| err.to_string())?;
        }
    }
    zip.finish().map_err(|err| err.to_string())?;
    Ok(cursor.into_inner())
}

pub(crate) fn render_markdown_bundle_bytes(
    response: &CompileResponse,
    manifest: &ExportManifest,
) -> Result<Vec<u8>, String> {
    let mut cursor = Cursor::new(Vec::new());
    let mut zip = ZipWriter::new(&mut cursor);
    let options = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);
    zip.start_file("document.md", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(response.compiled_markdown.as_bytes())
        .map_err(|err| err.to_string())?;
    zip.start_file("document.txt", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(export_text(response, &manifest.export_options).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.start_file("manifest.json", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(
        serde_json::to_string_pretty(manifest)
            .map_err(|err| err.to_string())?
            .as_bytes(),
    )
    .map_err(|err| err.to_string())?;
    for included in &manifest.included_files {
        if let Ok(bytes) = fs::read(&included.path) {
            let bundle_path = format!("includes/{}", safe_bundle_path(&included.path));
            zip.start_file(bundle_path, options)
                .map_err(|err| err.to_string())?;
            zip.write_all(&bytes).map_err(|err| err.to_string())?;
        }
    }
    zip.finish().map_err(|err| err.to_string())?;
    Ok(cursor.into_inner())
}

fn safe_bundle_path(path: &str) -> String {
    PathBuf::from(path)
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("include.md")
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || matches!(ch, '.' | '-' | '_') {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn render_docx_content_types(media: &[ExportMedia]) -> String {
    let mut defaults = vec![
        (
            "rels".to_string(),
            "application/vnd.openxmlformats-package.relationships+xml".to_string(),
        ),
        ("xml".to_string(), "application/xml".to_string()),
    ];
    for item in media {
        if !defaults
            .iter()
            .any(|(extension, _)| extension == &item.extension)
        {
            defaults.push((item.extension.clone(), item.content_type.clone()));
        }
    }
    let default_xml = defaults
        .iter()
        .map(|(extension, content_type)| {
            format!(
                r#"<Default Extension="{}" ContentType="{}"/>"#,
                escape_xml(extension),
                escape_xml(content_type)
            )
        })
        .collect::<String>();
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">{default_xml}<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/header1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/><Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/></Types>"#
    )
}

fn render_root_relationships(office_document_target: &str) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="{}"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/></Relationships>"#,
        escape_xml(office_document_target)
    )
}

fn render_docx_document_relationships(media: &[ExportMedia]) -> String {
    let media_relationships = media
        .iter()
        .map(|item| {
            format!(
                r#"<Relationship Id="{}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="{}"/>"#,
                escape_xml(&item.relationship_id),
                escape_xml(&item.path)
            )
        })
        .collect::<String>();
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdHeader1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Target="header1.xml"/><Relationship Id="rIdFooter1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/>{media_relationships}</Relationships>"#
    )
}

fn render_core_properties(response: &CompileResponse) -> String {
    let author = metadata_string(&response.metadata, "author")
        .or_else(|| metadata_string(&response.metadata, "approvedBy"))
        .unwrap_or_else(|| "NEditor".to_string());
    let version = metadata_string(&response.metadata, "version").unwrap_or_default();
    let classification = metadata_string(&response.metadata, "classification").unwrap_or_default();
    let keywords = [
        response.semantic.status.as_str(),
        version.as_str(),
        classification.as_str(),
    ]
    .into_iter()
    .filter(|value| !value.is_empty())
    .collect::<Vec<_>>()
    .join("; ");
    let description = format!(
        "Status: {}; Version: {}",
        response.semantic.status,
        if version.is_empty() {
            "unversioned"
        } else {
            version.as_str()
        }
    );
    let timestamp = Utc::now().to_rfc3339();
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>{}</dc:title><dc:creator>{}</dc:creator><dc:description>{}</dc:description><cp:keywords>{}</cp:keywords><cp:category>{}</cp:category><cp:lastModifiedBy>NEditor</cp:lastModifiedBy><dcterms:created xsi:type="dcterms:W3CDTF">{}</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">{}</dcterms:modified></cp:coreProperties>"#,
        escape_xml(&response.semantic.title),
        escape_xml(&author),
        escape_xml(&description),
        escape_xml(&keywords),
        escape_xml(&response.semantic.status),
        escape_xml(&timestamp),
        escape_xml(&timestamp)
    )
}

pub(crate) fn export_text(response: &CompileResponse, options: &Value) -> String {
    let mut lines = export_metadata_lines(response, options);
    lines.push(String::new());
    lines.push(export_body_text_from_ast(&response.document_ast));
    lines.extend(appendix_export_lines(response, options));
    lines.join("\n")
}

fn export_metadata_lines(response: &CompileResponse, options: &Value) -> Vec<String> {
    let (header, footer) = export_header_footer(response, options);
    let watermark = options
        .get("watermark")
        .and_then(Value::as_str)
        .unwrap_or("");
    let mut lines = Vec::new();
    if include_cover_page(options) {
        lines.push(format!("Cover: {}", response.semantic.title));
    }
    lines.push(format!("Status: {}", response.semantic.status));
    lines.push(format!("Header: {header}"));
    if !footer.is_empty() {
        lines.push(format!("Footer: {footer}"));
    }
    if include_page_numbers(options) {
        lines.push("Page 1 of 1".to_string());
    }
    lines.push(format!("Layout preset: {}", layout_preset(options)));
    lines.push(format!(
        "Syntax highlighting: {}",
        if include_syntax_highlighting(options) {
            "included"
        } else {
            "omitted"
        }
    ));
    for path in ["subtitle", "author", "date", "version", "brand.name"] {
        if let Some(value) = metadata_string(&response.metadata, path) {
            lines.push(value);
        }
    }
    if let Some(logo) = export_logo(&response.metadata) {
        lines.push(format!("Logo: {logo}"));
    }
    if !watermark.is_empty() {
        lines.push(format!("Watermark: {watermark}"));
    }
    lines
}

fn export_logo(metadata: &Value) -> Option<String> {
    metadata_string(metadata, "brand.logo")
        .or_else(|| metadata_string(metadata, "layout.logo"))
        .or_else(|| metadata_string(metadata, "logo"))
        .filter(|value| !value.trim().is_empty())
}

fn export_header_footer(response: &CompileResponse, options: &Value) -> (String, String) {
    let classification = metadata_string(&response.metadata, "classification").unwrap_or_default();
    let header = metadata_string(&response.metadata, "layout.header")
        .map(|template| render_export_template(&template, response, &classification))
        .unwrap_or_else(|| response.semantic.title.clone());
    let footer = metadata_string(&response.metadata, "layout.footer")
        .map(|template| render_export_template(&template, response, &classification))
        .unwrap_or_else(|| {
            if include_page_numbers(options) {
                "Page 1 of 1".to_string()
            } else {
                String::new()
            }
        });
    (header, footer)
}

fn boolean_option(options: &Value, name: &str, aliases: &[&str], default: bool) -> bool {
    std::iter::once(name)
        .chain(aliases.iter().copied())
        .find_map(|key| options.get(key).and_then(Value::as_bool))
        .unwrap_or(default)
}

fn include_styles(options: &Value) -> bool {
    boolean_option(options, "includeStyles", &[], true)
}

fn include_syntax_highlighting(options: &Value) -> bool {
    boolean_option(options, "includeSyntaxHighlighting", &[], true)
}

fn include_cover_page(options: &Value) -> bool {
    boolean_option(options, "coverPage", &["includeCoverPage"], true)
}

fn include_page_numbers(options: &Value) -> bool {
    boolean_option(options, "pageNumbers", &["includePageNumbers"], true)
}

fn layout_preset(options: &Value) -> &str {
    match options.get("layoutPreset").and_then(Value::as_str) {
        Some("compact") => "compact",
        Some("presentation") => "presentation",
        _ => "business",
    }
}

fn layout_page_size(metadata: &Value) -> String {
    metadata_string(metadata, "layout.pageSize")
        .or_else(|| metadata_string(metadata, "pageSize"))
        .map(|value| value.to_ascii_lowercase().replace([' ', '-'], ""))
        .and_then(|value| match value.as_str() {
            "letter" | "usletter" => Some("letter".to_string()),
            "legal" | "uslegal" => Some("legal".to_string()),
            "a4" => Some("a4".to_string()),
            _ => None,
        })
        .unwrap_or_else(|| "a4".to_string())
}

fn explicit_layout_margins(metadata: &Value) -> Option<String> {
    metadata_string(metadata, "layout.margins")
        .or_else(|| metadata_string(metadata, "margins"))
        .map(|value| value.to_ascii_lowercase().replace([' ', '-'], ""))
        .filter(|value| matches!(value.as_str(), "narrow" | "compact" | "normal" | "wide"))
}

fn highlight_code_blocks(html: &str) -> String {
    let mut output = String::with_capacity(html.len());
    let mut rest = html;
    while let Some(pre_start) = rest.find("<pre><code") {
        output.push_str(&rest[..pre_start]);
        let candidate = &rest[pre_start..];
        let Some(open_end) = candidate.find('>') else {
            output.push_str(candidate);
            return output;
        };
        let content_start = open_end + 1;
        let Some(close_start) = candidate[content_start..].find("</code></pre>") else {
            output.push_str(candidate);
            return output;
        };
        let close_start = content_start + close_start;
        let close_end = close_start + "</code></pre>".len();
        let open_tag = &candidate[..content_start];
        let code = &candidate[content_start..close_start];
        output.push_str(open_tag);
        output.push_str(&highlight_code_content(
            &decode_export_html_entities(code),
            code_language(open_tag),
        ));
        output.push_str("</code></pre>");
        rest = &candidate[close_end..];
    }
    output.push_str(rest);
    output
}

fn code_language(open_tag: &str) -> Option<&str> {
    let marker = "language-";
    let start = open_tag.find(marker)? + marker.len();
    let language = open_tag[start..]
        .split(|ch: char| !(ch.is_ascii_alphanumeric() || ch == '-' || ch == '_'))
        .next()
        .filter(|value| !value.is_empty())?;
    Some(language)
}

fn highlight_code_content(code: &str, language: Option<&str>) -> String {
    let mut output = String::with_capacity(code.len());
    let bytes = code.as_bytes();
    let mut index = 0usize;
    while index < bytes.len() {
        if is_comment_start(code, index, language) {
            let end = code[index..]
                .find('\n')
                .map(|offset| index + offset)
                .unwrap_or(code.len());
            push_span(&mut output, "syn-comment", &code[index..end]);
            index = end;
        } else if matches!(bytes[index], b'\'' | b'"') {
            let end = quoted_literal_end(code, index);
            push_span(&mut output, "syn-string", &code[index..end]);
            index = end;
        } else if bytes[index].is_ascii_digit() {
            let end = scan_while(code, index, |byte| {
                byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_')
            });
            push_span(&mut output, "syn-number", &code[index..end]);
            index = end;
        } else if bytes[index].is_ascii_alphabetic() || bytes[index] == b'_' {
            let end = scan_while(code, index, |byte| {
                byte.is_ascii_alphanumeric() || byte == b'_'
            });
            let token = &code[index..end];
            if is_keyword(token) {
                push_span(&mut output, "syn-keyword", token);
            } else {
                output.push_str(&escape_html(token));
            }
            index = end;
        } else {
            let ch = code[index..]
                .chars()
                .next()
                .expect("index should point at a char boundary");
            output.push_str(&escape_html(&ch.to_string()));
            index += ch.len_utf8();
        }
    }
    output
}

fn is_comment_start(code: &str, index: usize, language: Option<&str>) -> bool {
    let rest = &code[index..];
    if rest.starts_with("//") {
        return true;
    }
    if rest.starts_with('#') {
        return matches!(
            language,
            Some("py" | "python" | "sh" | "bash" | "zsh" | "yaml" | "yml" | "toml")
        );
    }
    false
}

fn quoted_literal_end(code: &str, start: usize) -> usize {
    let quote = code.as_bytes()[start];
    let mut index = start + 1;
    let bytes = code.as_bytes();
    while index < bytes.len() {
        if bytes[index] == b'\\' {
            index = (index + 2).min(bytes.len());
        } else if bytes[index] == quote {
            return index + 1;
        } else {
            index += 1;
        }
    }
    bytes.len()
}

fn scan_while(code: &str, start: usize, predicate: impl Fn(u8) -> bool) -> usize {
    let mut index = start;
    let bytes = code.as_bytes();
    while index < bytes.len() && predicate(bytes[index]) {
        index += 1;
    }
    index
}

fn is_keyword(token: &str) -> bool {
    matches!(
        token,
        "as" | "async"
            | "await"
            | "break"
            | "case"
            | "catch"
            | "class"
            | "const"
            | "continue"
            | "def"
            | "else"
            | "enum"
            | "export"
            | "false"
            | "fn"
            | "for"
            | "from"
            | "function"
            | "if"
            | "impl"
            | "import"
            | "in"
            | "let"
            | "match"
            | "mod"
            | "mut"
            | "return"
            | "self"
            | "struct"
            | "true"
            | "type"
            | "use"
            | "var"
            | "while"
    )
}

fn push_span(output: &mut String, class_name: &str, text: &str) {
    output.push_str("<span class=\"");
    output.push_str(class_name);
    output.push_str("\">");
    output.push_str(&escape_html(text));
    output.push_str("</span>");
}

fn include_glossary(options: &Value) -> bool {
    options
        .get("includeGlossary")
        .and_then(Value::as_bool)
        .unwrap_or(false)
}

fn include_comments(options: &Value) -> bool {
    options
        .get("includeComments")
        .and_then(Value::as_bool)
        .unwrap_or(false)
}

fn include_provenance(options: &Value) -> bool {
    options
        .get("includeProvenance")
        .and_then(Value::as_bool)
        .unwrap_or(false)
}

fn appendix_export_lines(response: &CompileResponse, options: &Value) -> Vec<String> {
    let mut lines = glossary_export_lines(response, options);
    lines.extend(comment_export_lines(response, options));
    lines.extend(provenance_export_lines(response, options));
    lines.extend(legal_disclaimer_export_lines(response));
    lines
}

fn glossary_export_lines(response: &CompileResponse, options: &Value) -> Vec<String> {
    if !include_glossary(options) || response.semantic.glossary.is_empty() {
        return Vec::new();
    }
    let mut lines = vec![String::new(), "Glossary".to_string()];
    lines.extend(
        response
            .semantic
            .glossary
            .iter()
            .map(|(term, definition)| format!("{term}: {definition}")),
    );
    lines
}

fn comment_export_lines(response: &CompileResponse, options: &Value) -> Vec<String> {
    if !include_comments(options)
        || (response.semantic.comments.is_empty() && response.semantic.change_notes.is_empty())
    {
        return Vec::new();
    }
    let mut lines = vec![String::new(), "Review Comments".to_string()];
    lines.extend(response.semantic.comments.iter().map(|comment| {
        let created_at = if comment.created_at.is_empty() {
            "undated"
        } else {
            comment.created_at.as_str()
        };
        let author = if comment.author.is_empty() {
            "local"
        } else {
            comment.author.as_str()
        };
        format!(
            "Line {} [{}] {} at {}: {}",
            comment.line, comment.state, author, created_at, comment.text
        )
    }));
    if !response.semantic.change_notes.is_empty() {
        lines.push(String::new());
        lines.push("Change Notes".to_string());
        lines.extend(response.semantic.change_notes.iter().map(|note| {
            let created_at = if note.created_at.is_empty() {
                "undated"
            } else {
                note.created_at.as_str()
            };
            let author = if note.author.is_empty() {
                "local"
            } else {
                note.author.as_str()
            };
            format!(
                "Line {} {} at {}: {}",
                note.line, author, created_at, note.text
            )
        }));
    }
    lines
}

fn provenance_export_lines(response: &CompileResponse, options: &Value) -> Vec<String> {
    if !include_provenance(options)
        || (response.semantic.ai_sources.is_empty()
            && response.semantic.ai_assisted_sections.is_empty())
    {
        return Vec::new();
    }
    let mut lines = vec![String::new(), "AI Provenance".to_string()];
    lines.extend(response.semantic.ai_sources.iter().map(|source| {
        let provider = empty_as(source.provider.as_str(), "unknown provider");
        let model = empty_as(source.model.as_str(), "unknown model");
        let date = empty_as(source.date.as_str(), "undated");
        let reviewer = empty_as(source.reviewed_by.as_str(), "unreviewed");
        let reviewed_at = empty_as(source.reviewed_at.as_str(), "undated");
        let summary = empty_as(source.prompt_summary.as_str(), "no prompt summary");
        format!(
            "{provider} / {model} on {date}; status: {}; reviewed by: {reviewer} on {reviewed_at}; prompt: {summary}",
            source.status
        )
    }));
    lines.extend(response.semantic.ai_assisted_sections.iter().map(|section| {
        let reviewer = empty_as(section.reviewed_by.as_str(), "unreviewed");
        let reviewed_at = empty_as(section.reviewed_at.as_str(), "undated");
        let source = empty_as(section.source.as_str(), "unspecified source");
        let summary = empty_as(section.prompt_summary.as_str(), "no prompt summary");
        format!(
            "Section '{}' at line {}: status {}; reviewed by {reviewer} on {reviewed_at}; source: {source}; prompt: {summary}",
            section.heading, section.line, section.status
        )
    }));
    lines
}

fn legal_disclaimer_export_lines(response: &CompileResponse) -> Vec<String> {
    let Some(disclaimer) = metadata_string(&response.metadata, "legalDisclaimer")
        .filter(|value| !value.trim().is_empty())
    else {
        return Vec::new();
    };
    vec![String::new(), "Legal Disclaimer".to_string(), disclaimer]
}

fn empty_as<'a>(value: &'a str, fallback: &'a str) -> &'a str {
    if value.is_empty() {
        fallback
    } else {
        value
    }
}

fn html_appendix_sections(response: &CompileResponse, options: &Value) -> String {
    [
        html_glossary_section(response, options),
        html_comments_section(response, options),
        html_provenance_section(response, options),
        html_legal_disclaimer_section(response),
    ]
    .join("")
}

fn html_glossary_section(response: &CompileResponse, options: &Value) -> String {
    if !include_glossary(options) || response.semantic.glossary.is_empty() {
        return String::new();
    }
    let entries = response
        .semantic
        .glossary
        .iter()
        .map(|(term, definition)| {
            format!(
                "<dt>{}</dt><dd>{}</dd>",
                escape_html(term),
                escape_html(definition)
            )
        })
        .collect::<String>();
    format!("<section class=\"export-glossary\"><h2>Glossary</h2><dl>{entries}</dl></section>")
}

fn html_comments_section(response: &CompileResponse, options: &Value) -> String {
    if !include_comments(options)
        || (response.semantic.comments.is_empty() && response.semantic.change_notes.is_empty())
    {
        return String::new();
    }
    let entries = response
        .semantic
        .comments
        .iter()
        .map(|comment| {
            let created_at = empty_as(comment.created_at.as_str(), "undated");
            let author = empty_as(comment.author.as_str(), "local");
            format!(
                "<li><strong>Line {}</strong> <span>{}</span> <em>{} at {}</em><p>{}</p></li>",
                comment.line,
                escape_html(&comment.state),
                escape_html(author),
                escape_html(created_at),
                escape_html(&comment.text)
            )
        })
        .collect::<String>();
    let change_entries = response
        .semantic
        .change_notes
        .iter()
        .map(|note| {
            let created_at = empty_as(note.created_at.as_str(), "undated");
            let author = empty_as(note.author.as_str(), "local");
            format!(
                "<li><strong>Line {}</strong> <em>{} at {}</em><p>{}</p></li>",
                note.line,
                escape_html(author),
                escape_html(created_at),
                escape_html(&note.text)
            )
        })
        .collect::<String>();
    let changes = if change_entries.is_empty() {
        String::new()
    } else {
        format!("<h3>Change Notes</h3><ol>{change_entries}</ol>")
    };
    format!(
        "<section class=\"export-comments\"><h2>Review Comments</h2><ol>{entries}</ol>{changes}</section>"
    )
}

fn html_provenance_section(response: &CompileResponse, options: &Value) -> String {
    if !include_provenance(options)
        || (response.semantic.ai_sources.is_empty()
            && response.semantic.ai_assisted_sections.is_empty())
    {
        return String::new();
    }
    let source_entries = response
        .semantic
        .ai_sources
        .iter()
        .map(|source| {
            format!(
                "<li><strong>{}</strong> <span>{}</span><p>{}; reviewed by {} on {}; {}; prompt: {}</p></li>",
                escape_html(empty_as(source.provider.as_str(), "unknown provider")),
                escape_html(empty_as(source.model.as_str(), "unknown model")),
                escape_html(empty_as(source.date.as_str(), "undated")),
                escape_html(empty_as(source.reviewed_by.as_str(), "unreviewed")),
                escape_html(empty_as(source.reviewed_at.as_str(), "undated")),
                escape_html(&source.status),
                escape_html(empty_as(
                    source.prompt_summary.as_str(),
                    "no prompt summary"
                ))
            )
        })
        .collect::<String>();
    let section_entries = response
        .semantic
        .ai_assisted_sections
        .iter()
        .map(|section| {
            format!(
                "<li><strong>{}</strong> <span>line {}</span><p>{}; reviewed by {} on {}; source: {}; prompt: {}</p></li>",
                escape_html(&section.heading),
                section.line,
                escape_html(&section.status),
                escape_html(empty_as(section.reviewed_by.as_str(), "unreviewed")),
                escape_html(empty_as(section.reviewed_at.as_str(), "undated")),
                escape_html(empty_as(section.source.as_str(), "unspecified source")),
                escape_html(empty_as(section.prompt_summary.as_str(), "no prompt summary"))
            )
        })
        .collect::<String>();
    let entries = format!("{source_entries}{section_entries}");
    format!(
        "<section class=\"export-provenance\"><h2>AI Provenance</h2><ol>{entries}</ol></section>"
    )
}

fn html_legal_disclaimer_section(response: &CompileResponse) -> String {
    let Some(disclaimer) = metadata_string(&response.metadata, "legalDisclaimer")
        .filter(|value| !value.trim().is_empty())
    else {
        return String::new();
    };
    format!(
        "<section class=\"export-legal\"><h2>Legal Disclaimer</h2><p>{}</p></section>",
        escape_html(&disclaimer)
    )
}

fn render_docx_document(
    response: &CompileResponse,
    options: &Value,
    media: &[ExportMedia],
) -> String {
    let mut body = String::new();
    for line in export_metadata_lines(response, options) {
        body.push_str(&docx_paragraph(&line));
    }
    body.push_str(&docx_page_break());
    for block in &response.document_ast.blocks {
        body.push_str(&render_docx_block(block, media));
    }
    for line in appendix_export_lines(response, options) {
        if matches!(
            line.as_str(),
            "Glossary" | "Review Comments" | "AI Provenance" | "Legal Disclaimer"
        ) {
            body.push_str(&docx_heading(1, &line));
        } else {
            body.push_str(&docx_paragraph(&line));
        }
    }
    let (page_width, page_height, margin_top, margin_right, margin_bottom, margin_left) =
        docx_page_layout(response, options);
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"><w:body>{body}<w:sectPr><w:headerReference w:type="default" r:id="rIdHeader1"/><w:footerReference w:type="default" r:id="rIdFooter1"/><w:pgSz w:w="{page_width}" w:h="{page_height}"/><w:pgMar w:top="{margin_top}" w:right="{margin_right}" w:bottom="{margin_bottom}" w:left="{margin_left}"/></w:sectPr></w:body></w:document>"#
    )
}

fn render_docx_header(response: &CompileResponse, options: &Value) -> String {
    let (header, _) = export_header_footer(response, options);
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><w:hdr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">{}</w:hdr>"#,
        docx_paragraph(&header)
    )
}

fn render_docx_footer(response: &CompileResponse, options: &Value) -> String {
    let (_, footer) = export_header_footer(response, options);
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><w:ftr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">{}</w:ftr>"#,
        docx_paragraph(&footer)
    )
}

fn render_docx_block(block: &DocumentBlock, media: &[ExportMedia]) -> String {
    match block {
        DocumentBlock::Heading { level, text, .. } => docx_heading(*level, text),
        DocumentBlock::Paragraph { text, .. } => docx_paragraph(text),
        DocumentBlock::List { ordered, items, .. } => docx_list(*ordered, items),
        DocumentBlock::TaskList { items, .. } => docx_task_list(items),
        DocumentBlock::BlockQuote { text, .. } => docx_paragraph(&format!("Quote: {text}")),
        DocumentBlock::CodeBlock { language, code, .. } => {
            let label = language
                .as_deref()
                .filter(|value| !value.is_empty())
                .map(|value| format!("Code ({value})"))
                .unwrap_or_else(|| "Code".to_string());
            format!("{}{}", docx_paragraph(&label), docx_paragraph(code))
        }
        DocumentBlock::Table {
            id,
            caption,
            headers,
            alignments,
            rows,
            ..
        } => {
            let mut output = String::new();
            if id.is_some() || caption.is_some() {
                output.push_str(&docx_paragraph(&table_export_line(id, caption, headers)));
            }
            output.push_str(&docx_table(headers, alignments, rows));
            output
        }
        DocumentBlock::Figure {
            id,
            src,
            alt,
            caption,
            source,
            ..
        } => docx_figure(id, src, alt, caption, source.as_ref(), media),
        DocumentBlock::Equation {
            id, caption, text, ..
        } => docx_paragraph(&equation_export_line(id, text, caption)),
        DocumentBlock::Layout { directive, .. } if directive == "page-break" => docx_page_break(),
        DocumentBlock::Layout {
            directive, options, ..
        } if directive == "section-break" || layout_columns(options).is_some() => {
            docx_section_break(options)
        }
        DocumentBlock::Layout {
            directive, options, ..
        } => docx_paragraph(&format!("Layout: {directive} {options}").trim().to_string()),
        DocumentBlock::Callout {
            callout_type,
            title,
            text,
            ..
        } => docx_paragraph(&callout_export_line(callout_type, title, text)),
        DocumentBlock::Footnotes { entries, .. } => {
            let mut output = docx_heading(1, "Footnotes");
            for entry in entries {
                output.push_str(&docx_paragraph(&format!(
                    "{}. {}",
                    entry.number, entry.text
                )));
            }
            output
        }
        DocumentBlock::RawHtml { html, .. } => raw_html_export_lines(html)
            .into_iter()
            .map(|line| docx_paragraph(&line))
            .collect::<String>(),
    }
}

fn docx_heading(level: usize, text: &str) -> String {
    let style = format!("Heading{}", level.clamp(1, 6));
    format!(
        r#"<w:p><w:pPr><w:pStyle w:val="{style}"/></w:pPr><w:r><w:t>{}</w:t></w:r></w:p>"#,
        escape_xml(text)
    )
}

fn docx_paragraph(text: &str) -> String {
    format!(r#"<w:p><w:r><w:t>{}</w:t></w:r></w:p>"#, escape_xml(text))
}

fn docx_list(ordered: bool, items: &[String]) -> String {
    items
        .iter()
        .enumerate()
        .map(|(index, item)| {
            let marker = if ordered {
                format!("{}.", index + 1)
            } else {
                "-".to_string()
            };
            docx_paragraph(&format!("{marker} {item}"))
        })
        .collect::<String>()
}

fn docx_task_list(items: &[crate::document_ast::TaskListItem]) -> String {
    items
        .iter()
        .map(|item| {
            docx_paragraph(&format!(
                "[{}] {}",
                if item.checked { "x" } else { " " },
                item.text
            ))
        })
        .collect::<String>()
}

fn docx_page_break() -> String {
    r#"<w:p><w:r><w:br w:type="page"/></w:r></w:p>"#.to_string()
}

fn docx_section_break(options: &str) -> String {
    let columns = layout_columns(options).unwrap_or(1);
    format!(
        r#"<w:p><w:pPr><w:sectPr><w:cols w:num="{columns}" w:space="720"/></w:sectPr></w:pPr></w:p>"#
    )
}

fn docx_page_layout(response: &CompileResponse, options: &Value) -> (u32, u32, u32, u32, u32, u32) {
    let (width, height) = match layout_page_size(&response.metadata).as_str() {
        "letter" => (12240, 15840),
        "legal" => (12240, 20160),
        _ => (11906, 16838),
    };
    let margin = match explicit_layout_margins(&response.metadata).as_deref() {
        Some("narrow") | Some("compact") => 720,
        Some("wide") => 1800,
        Some("normal") => 1440,
        _ => match layout_preset(options) {
            "compact" => 1080,
            "presentation" => 1200,
            _ => 1440,
        },
    };
    (width, height, margin, margin, margin, margin)
}

fn docx_table(headers: &[String], alignments: &[String], rows: &[Vec<String>]) -> String {
    let mut table = String::from(
        r#"<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/><w:tblW w:w="0" w:type="auto"/></w:tblPr>"#,
    );
    table.push_str(&docx_table_row(headers, alignments));
    for row in rows {
        table.push_str(&docx_table_row(row, alignments));
    }
    table.push_str("</w:tbl>");
    table
}

fn docx_table_row(cells: &[String], alignments: &[String]) -> String {
    let cells = cells
        .iter()
        .enumerate()
        .map(|(index, cell)| docx_cell(cell, alignments.get(index).map(String::as_str)))
        .collect::<String>();
    format!("<w:tr>{cells}</w:tr>")
}

fn docx_cell(text: &str, alignment: Option<&str>) -> String {
    let alignment = match alignment {
        Some("center") => r#"<w:pPr><w:jc w:val="center"/></w:pPr>"#,
        Some("right") => r#"<w:pPr><w:jc w:val="right"/></w:pPr>"#,
        _ => "",
    };
    format!(
        r#"<w:tc><w:tcPr><w:tcW w:w="2400" w:type="dxa"/></w:tcPr><w:p>{alignment}<w:r><w:t>{}</w:t></w:r></w:p></w:tc>"#,
        escape_xml(text)
    )
}

fn docx_figure(
    id: &Option<String>,
    src: &Option<String>,
    alt: &Option<String>,
    caption: &Option<String>,
    source: Option<&AstSourceRange>,
    media: &[ExportMedia],
) -> String {
    let caption_text = figure_export_line(id, src, alt, caption);
    let Some(src) = src else {
        return docx_paragraph(&caption_text);
    };
    let Some((media_index, item)) = media.iter().enumerate().find(|(_, item)| {
        item.source == *src
            && item.source_file.as_deref() == source.map(|range| range.source_file.as_str())
    }) else {
        return docx_paragraph(&caption_text);
    };
    let doc_pr_id = media_index + 1;
    let name = caption
        .as_deref()
        .or(alt.as_deref())
        .or(id.as_deref())
        .unwrap_or("Figure");
    let drawing = format!(
        r#"<w:p><w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="4320000" cy="2430000"/><wp:docPr id="{doc_pr_id}" name="{}"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="{doc_pr_id}" name="{}"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="{}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="4320000" cy="2430000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>"#,
        escape_xml(name),
        escape_xml(name),
        escape_xml(&item.relationship_id)
    );
    format!("{drawing}{}", docx_paragraph(&caption_text))
}

fn collect_docx_media(response: &CompileResponse) -> Vec<ExportMedia> {
    let mut media = Vec::new();
    for block in &response.document_ast.blocks {
        let DocumentBlock::Figure {
            src: Some(src),
            source,
            ..
        } = block
        else {
            continue;
        };
        let source_file = source.as_ref().map(|range| range.source_file.clone());
        if media
            .iter()
            .any(|item: &ExportMedia| item.source == *src && item.source_file == source_file)
        {
            continue;
        }
        let Some((extension, content_type, bytes)) = parse_export_image(src, source.as_ref())
        else {
            continue;
        };
        let index = media.len() + 1;
        media.push(ExportMedia {
            source: src.clone(),
            source_file,
            relationship_id: format!("rIdImage{index}"),
            path: format!("media/image{index}.{extension}"),
            extension,
            content_type,
            bytes,
        });
    }
    media
}

fn collect_pptx_media(response: &CompileResponse) -> Vec<ExportMedia> {
    collect_docx_media(response)
}

fn parse_export_image(
    src: &str,
    source: Option<&AstSourceRange>,
) -> Option<(String, String, Vec<u8>)> {
    parse_image_data_uri(src).or_else(|| read_local_export_image(src, source))
}

fn parse_image_data_uri(src: &str) -> Option<(String, String, Vec<u8>)> {
    let data = src.strip_prefix("data:")?;
    let (metadata, payload) = data.split_once(',')?;
    let mut parts = metadata.split(';');
    let content_type = parts.next()?.to_ascii_lowercase();
    if !parts.any(|part| part.eq_ignore_ascii_case("base64")) {
        return None;
    }
    let extension = image_extension_for_content_type(&content_type)?;
    Some((extension.to_string(), content_type, decode_base64(payload)?))
}

fn read_local_export_image(
    src: &str,
    source: Option<&AstSourceRange>,
) -> Option<(String, String, Vec<u8>)> {
    if src.starts_with("data:") || src.contains("://") || src.starts_with('#') {
        return None;
    }
    let path = local_export_image_path(src, source)?;
    let extension = path
        .extension()
        .and_then(|extension| extension.to_str())
        .map(|extension| extension.to_ascii_lowercase())?;
    let content_type = image_content_type_for_extension(&extension)?;
    let bytes = fs::read(path).ok()?;
    Some((extension, content_type.to_string(), bytes))
}

fn local_export_image_path(src: &str, source: Option<&AstSourceRange>) -> Option<PathBuf> {
    let path = PathBuf::from(src);
    if path.is_absolute() {
        return Some(path);
    }
    let source_file = source?.source_file.as_str();
    Some(Path::new(source_file).parent()?.join(path))
}

fn image_extension_for_content_type(content_type: &str) -> Option<&'static str> {
    match content_type {
        "image/svg+xml" => Some("svg"),
        "image/png" => Some("png"),
        "image/jpeg" | "image/jpg" => Some("jpg"),
        _ => None,
    }
}

fn image_content_type_for_extension(extension: &str) -> Option<&'static str> {
    match extension {
        "svg" => Some("image/svg+xml"),
        "png" => Some("image/png"),
        "jpg" | "jpeg" => Some("image/jpeg"),
        _ => None,
    }
}

fn decode_base64(input: &str) -> Option<Vec<u8>> {
    let mut bits = 0u32;
    let mut bit_count = 0u8;
    let mut output = Vec::new();
    for byte in input.bytes().filter(|byte| !byte.is_ascii_whitespace()) {
        if byte == b'=' {
            break;
        }
        let value = base64_value(byte)? as u32;
        bits = (bits << 6) | value;
        bit_count += 6;
        while bit_count >= 8 {
            bit_count -= 8;
            output.push(((bits >> bit_count) & 0xff) as u8);
        }
    }
    Some(output)
}

fn base64_value(byte: u8) -> Option<u8> {
    match byte {
        b'A'..=b'Z' => Some(byte - b'A'),
        b'a'..=b'z' => Some(byte - b'a' + 26),
        b'0'..=b'9' => Some(byte - b'0' + 52),
        b'+' => Some(62),
        b'/' => Some(63),
        _ => None,
    }
}

fn build_pdf_pages(response: &CompileResponse, options: &Value) -> Vec<Vec<String>> {
    let mut pages = vec![export_metadata_lines(response, options)];
    let mut current = Vec::new();
    for block in &response.document_ast.blocks {
        match block {
            DocumentBlock::Layout { directive, .. } if directive == "page-break" => {
                if !current.is_empty() {
                    pages.push(current);
                    current = Vec::new();
                }
            }
            DocumentBlock::Layout {
                directive, options, ..
            } if directive == "section-break" => {
                if !current.is_empty() {
                    pages.push(current);
                    current = Vec::new();
                }
                current.extend(layout_export_lines(directive, options));
            }
            _ => current.extend(block_export_lines(block)),
        }
    }
    if !current.is_empty() {
        pages.push(current);
    }
    for appendix in appendix_pages(response, options) {
        pages.push(appendix);
    }
    pages
}

fn appendix_pages(response: &CompileResponse, options: &Value) -> Vec<Vec<String>> {
    [
        glossary_export_lines(response, options),
        comment_export_lines(response, options),
        provenance_export_lines(response, options),
        legal_disclaimer_export_lines(response),
    ]
    .into_iter()
    .filter(|lines| !lines.is_empty())
    .collect()
}

#[derive(Debug)]
struct PptxSlide {
    title: String,
    lines: Vec<String>,
    media_refs: Vec<MediaRef>,
    notes: Vec<String>,
}

#[derive(Clone, Debug)]
struct MediaRef {
    source: String,
    source_file: Option<String>,
}

impl PptxSlide {
    fn new(title: impl Into<String>) -> Self {
        Self {
            title: title.into(),
            lines: Vec::new(),
            media_refs: Vec::new(),
            notes: Vec::new(),
        }
    }

    fn with_lines(title: impl Into<String>, lines: Vec<String>) -> Self {
        Self {
            title: title.into(),
            lines,
            media_refs: Vec::new(),
            notes: Vec::new(),
        }
    }
}

fn build_pptx_slides(response: &CompileResponse, options: &Value) -> Vec<PptxSlide> {
    let mut slides = vec![PptxSlide::with_lines(
        response.semantic.title.clone(),
        export_metadata_lines(response, options)
            .into_iter()
            .filter(|line| !line.starts_with("Cover: "))
            .collect(),
    )];
    let include_agenda = include_pptx_agenda(response, options);
    if include_agenda {
        let lines = response
            .semantic
            .outline
            .iter()
            .filter(|heading| heading.level <= 2)
            .map(|heading| {
                format!(
                    "{}{}",
                    "  ".repeat(heading.level.saturating_sub(1)),
                    heading.text
                )
            })
            .collect::<Vec<_>>();
        if !lines.is_empty() {
            slides.push(PptxSlide::with_lines("Agenda", lines));
        }
    }
    let mut current: Option<PptxSlide> = None;
    let mut skip_next_toc_body = false;

    for block in &response.document_ast.blocks {
        if skip_next_toc_body {
            skip_next_toc_body = false;
            if is_generated_toc_body(block) {
                continue;
            }
        }
        if include_agenda && is_generated_toc_heading(block) {
            skip_next_toc_body = true;
            continue;
        }
        match block {
            DocumentBlock::Heading { level, text, .. } if *level <= 2 => {
                if let Some(slide) = current.take() {
                    if !slide.lines.is_empty() || slide.title != "Continued" {
                        slides.push(slide);
                    }
                }
                current = Some(PptxSlide::new(text.clone()));
            }
            DocumentBlock::Layout { directive, .. } if directive == "page-break" => {
                if let Some(slide) = current.take() {
                    slides.push(slide);
                }
                current = Some(PptxSlide::new("Continued"));
            }
            DocumentBlock::Layout {
                directive, options, ..
            } if directive == "section-break" => {
                if let Some(slide) = current.take() {
                    if !slide.lines.is_empty() || slide.title != "Continued" {
                        slides.push(slide);
                    }
                }
                current = Some(PptxSlide::with_lines(
                    "Section",
                    layout_export_lines(directive, options),
                ));
            }
            DocumentBlock::Layout {
                directive, options, ..
            } if directive == "slide" => {
                if let Some(slide) = current.take() {
                    if !slide.lines.is_empty() || slide.title != "Continued" {
                        slides.push(slide);
                    }
                }
                let mut slide = PptxSlide::new(slide_title_from_options(options));
                slide.notes = slide_notes_from_options(options);
                current = Some(slide);
            }
            _ => {
                if current.is_none() {
                    current = Some(PptxSlide::new("Document"));
                }
                if let Some(slide) = current.as_mut() {
                    add_block_to_pptx_slide(slide, block);
                }
            }
        }
    }

    if let Some(slide) = current {
        if !slide.lines.is_empty() || slide.title != "Continued" {
            slides.push(slide);
        }
    }
    for appendix in appendix_pages(response, options) {
        let title = appendix
            .iter()
            .find(|line| {
                matches!(
                    line.as_str(),
                    "Glossary" | "Review Comments" | "AI Provenance"
                )
            })
            .cloned()
            .unwrap_or_else(|| "Appendix".to_string());
        slides.push(PptxSlide::with_lines(
            title,
            appendix
                .into_iter()
                .filter(|line| !line.is_empty())
                .filter(|line| {
                    !matches!(
                        line.as_str(),
                        "Glossary" | "Review Comments" | "AI Provenance"
                    )
                })
                .collect(),
        ));
    }
    slides
        .into_iter()
        .map(|mut slide| {
            if slide.lines.is_empty() {
                slide.lines.push("No body content".to_string());
            }
            slide.lines.truncate(14);
            slide
        })
        .collect()
}

fn include_pptx_agenda(response: &CompileResponse, options: &Value) -> bool {
    options
        .get("includeAgenda")
        .and_then(Value::as_bool)
        .or_else(|| response.metadata.get("toc").and_then(Value::as_bool))
        .unwrap_or(false)
}

fn add_block_to_pptx_slide(slide: &mut PptxSlide, block: &DocumentBlock) {
    slide.lines.extend(block_export_lines(block));
    if let DocumentBlock::Figure {
        src: Some(src),
        source,
        ..
    } = block
    {
        slide.media_refs.push(MediaRef {
            source: src.clone(),
            source_file: source.as_ref().map(|range| range.source_file.clone()),
        });
    }
}

fn is_generated_toc_heading(block: &DocumentBlock) -> bool {
    matches!(
        block,
        DocumentBlock::Heading { level, text, .. }
            if *level == 2 && text == "Table of Contents"
    )
}

fn is_generated_toc_body(block: &DocumentBlock) -> bool {
    matches!(
        block,
        DocumentBlock::Paragraph { text, .. }
            if text.trim_start().starts_with("- [") && text.contains("](#")
    )
}

fn block_export_lines(block: &DocumentBlock) -> Vec<String> {
    match block {
        DocumentBlock::Heading { level, text, .. } => {
            vec![format!("{} {text}", "#".repeat(*level))]
        }
        DocumentBlock::Paragraph { text, .. } => vec![text.clone()],
        DocumentBlock::BlockQuote { text, .. } => {
            text.lines().map(|line| format!("> {line}")).collect()
        }
        DocumentBlock::CodeBlock { language, code, .. } => {
            let mut lines = vec![format!("```{}", language.as_deref().unwrap_or(""))];
            lines.extend(code.lines().map(ToString::to_string));
            lines.push("```".to_string());
            lines
        }
        DocumentBlock::List { ordered, items, .. } => items
            .iter()
            .enumerate()
            .map(|(index, item)| {
                if *ordered {
                    format!("{}. {item}", index + 1)
                } else {
                    format!("- {item}")
                }
            })
            .collect(),
        DocumentBlock::TaskList { items, .. } => items
            .iter()
            .map(|item| format!("- [{}] {}", if item.checked { "x" } else { " " }, item.text))
            .collect(),
        DocumentBlock::Table {
            id,
            caption,
            headers,
            alignments: _,
            rows,
            ..
        } => {
            let mut lines = vec![table_export_line(id, caption, headers)];
            lines.extend(rows.iter().map(|row| row.join(" | ")));
            lines
        }
        DocumentBlock::Figure {
            id,
            src,
            alt,
            caption,
            ..
        } => vec![figure_export_line(id, src, alt, caption)],
        DocumentBlock::Equation {
            id, caption, text, ..
        } => vec![equation_export_line(id, text, caption)],
        DocumentBlock::Layout {
            directive, options, ..
        } => layout_export_lines(directive, options),
        DocumentBlock::Callout {
            callout_type,
            title,
            text,
            ..
        } => vec![callout_export_line(callout_type, title, text)],
        DocumentBlock::Footnotes { entries, .. } => {
            let mut lines = vec!["Footnotes".to_string()];
            lines.extend(
                entries
                    .iter()
                    .map(|entry| format!("{}. {}", entry.number, entry.text)),
            );
            lines
        }
        DocumentBlock::RawHtml { html, .. } => raw_html_export_lines(html),
    }
}

fn raw_html_export_lines(html: &str) -> Vec<String> {
    if html.contains("role=\"doc-endnotes\"") || html.contains("class=\"footnotes\"") {
        return vec!["Footnotes".to_string()];
    }
    let text = decode_export_html_entities(&strip_export_html_tags(html))
        .trim()
        .trim_end_matches(" back")
        .trim()
        .to_string();
    if text.is_empty() {
        Vec::new()
    } else {
        vec![text]
    }
}

fn strip_export_html_tags(html: &str) -> String {
    let mut output = String::new();
    let mut in_tag = false;
    for ch in html.chars() {
        match ch {
            '<' => in_tag = true,
            '>' => {
                in_tag = false;
                output.push(' ');
            }
            _ if !in_tag => output.push(ch),
            _ => {}
        }
    }
    output.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn decode_export_html_entities(text: &str) -> String {
    text.replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&amp;", "&")
}

fn layout_export_lines(directive: &str, options: &str) -> Vec<String> {
    let summary = layout_summary(options);
    let label = match directive {
        "section-break" => "Section break",
        "slide" => "Slide",
        "layout" => "Layout",
        "page-break" => "Page break",
        _ => "Layout directive",
    };
    vec![format!("{label}{summary}")]
}

fn layout_summary(options: &str) -> String {
    let mut parts = Vec::new();
    if let Some(columns) = layout_columns(options) {
        parts.push(format!("columns={columns}"));
    }
    if parts.is_empty() {
        let trimmed = options.trim();
        if trimmed.is_empty() {
            String::new()
        } else {
            format!(": {trimmed}")
        }
    } else {
        format!(": {}", parts.join(", "))
    }
}

fn slide_title_from_options(options: &str) -> String {
    layout_option_text(options, "title").unwrap_or_else(|| {
        let trimmed = options.trim();
        if trimmed.is_empty() {
            "Slide".to_string()
        } else {
            trimmed.to_string()
        }
    })
}

fn slide_notes_from_options(options: &str) -> Vec<String> {
    ["notes", "speakerNotes", "speaker_notes"]
        .iter()
        .find_map(|key| layout_option_text(options, key))
        .map(|value| {
            value
                .replace("\\n", "\n")
                .lines()
                .map(str::trim)
                .filter(|line| !line.is_empty())
                .map(ToString::to_string)
                .collect()
        })
        .unwrap_or_default()
}

fn layout_option_text(text: &str, key: &str) -> Option<String> {
    for line in text.lines() {
        if let Some((candidate, value)) = line.split_once(':') {
            if candidate.trim() == key {
                return Some(value.trim().trim_matches('"').to_string());
            }
        }
    }
    let prefix = format!("{key}=");
    let start = text.find(&prefix)? + prefix.len();
    let value = &text[start..];
    if let Some(quoted) = value.strip_prefix('"') {
        return quoted.split_once('"').map(|(title, _)| title.to_string());
    }
    value
        .split_whitespace()
        .next()
        .filter(|value| !value.is_empty())
        .map(|value| value.trim_matches('"').to_string())
}

fn layout_columns(options: &str) -> Option<usize> {
    for line in options.lines() {
        if let Some((key, value)) = line.split_once(':') {
            if key.trim() == "columns" {
                return parse_layout_columns(value);
            }
        }
    }
    for part in options.split_whitespace() {
        if let Some((key, value)) = part.split_once('=') {
            if key.trim() == "columns" {
                return parse_layout_columns(value);
            }
        }
    }
    None
}

fn parse_layout_columns(value: &str) -> Option<usize> {
    let columns = value.trim().trim_matches('"').parse::<usize>().ok()?;
    (columns > 0).then_some(columns)
}

fn callout_export_line(callout_type: &str, title: &str, text: &str) -> String {
    let mut parts = vec![format!("Callout: {callout_type}")];
    if !title.is_empty() {
        parts.push(title.to_string());
    }
    if !text.is_empty() {
        parts.push(text.to_string());
    }
    parts.join(": ")
}

fn figure_export_line(
    id: &Option<String>,
    src: &Option<String>,
    alt: &Option<String>,
    caption: &Option<String>,
) -> String {
    let mut parts = vec!["Figure".to_string()];
    if let Some(id) = id {
        parts.push(id.clone());
    }
    if let Some(caption) = caption {
        parts.push(caption.clone());
    }
    if let Some(alt) = alt {
        parts.push(alt.clone());
    }
    if let Some(src) = src {
        parts.push(format!("({src})"));
    }
    parts.join(": ")
}

fn table_export_line(id: &Option<String>, caption: &Option<String>, headers: &[String]) -> String {
    let mut parts = vec!["Table".to_string()];
    if let Some(id) = id {
        parts.push(id.clone());
    }
    if let Some(caption) = caption {
        parts.push(caption.clone());
    }
    if parts.len() == 1 {
        parts.push(headers.join(" | "));
    }
    parts.join(": ")
}

fn equation_export_line(id: &Option<String>, text: &str, caption: &Option<String>) -> String {
    let mut parts = vec!["Equation".to_string()];
    if let Some(id) = id {
        parts.push(id.clone());
    }
    if !text.is_empty() {
        parts.push(text.to_string());
    }
    if let Some(caption) = caption {
        parts.push(caption.clone());
    }
    parts.join(": ")
}

fn render_pptx_content_types(slides: &[PptxSlide], media: &[ExportMedia]) -> String {
    let mut defaults = vec![
        (
            "rels".to_string(),
            "application/vnd.openxmlformats-package.relationships+xml".to_string(),
        ),
        ("xml".to_string(), "application/xml".to_string()),
    ];
    for item in media {
        if !defaults
            .iter()
            .any(|(extension, _)| extension == &item.extension)
        {
            defaults.push((item.extension.clone(), item.content_type.clone()));
        }
    }
    let default_xml = defaults
        .iter()
        .map(|(extension, content_type)| {
            format!(
                r#"<Default Extension="{}" ContentType="{}"/>"#,
                escape_xml(extension),
                escape_xml(content_type)
            )
        })
        .collect::<String>();
    let slide_overrides = (1..=slides.len())
        .map(|index| format!(r#"<Override PartName="/ppt/slides/slide{index}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>"#))
        .collect::<String>();
    let notes_overrides = slides
        .iter()
        .enumerate()
        .filter(|(_, slide)| !slide.notes.is_empty())
        .map(|(index, _)| {
            let note_index = index + 1;
            format!(r#"<Override PartName="/ppt/notesSlides/notesSlide{note_index}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.notesSlide+xml"/>"#)
        })
        .collect::<String>();
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">{default_xml}<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>{slide_overrides}{notes_overrides}</Types>"#
    )
}

fn render_pptx_relationships(slide_count: usize) -> String {
    let relationships = (1..=slide_count)
        .map(|index| format!(r#"<Relationship Id="rId{index}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide{index}.xml"/>"#))
        .collect::<String>();
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">{relationships}</Relationships>"#
    )
}

fn render_pptx_slide_relationships(
    media: &[&ExportMedia],
    notes_slide_index: Option<usize>,
) -> String {
    let mut relationships = media
        .iter()
        .map(|item| {
            format!(
                r#"<Relationship Id="{}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../{}"/>"#,
                escape_xml(&item.relationship_id),
                escape_xml(&item.path)
            )
        })
        .collect::<Vec<_>>();
    if let Some(index) = notes_slide_index {
        relationships.push(format!(
            r#"<Relationship Id="rIdNotes" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesSlide" Target="../notesSlides/notesSlide{index}.xml"/>"#
        ));
    }
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">{}</Relationships>"#,
        relationships.join("")
    )
}

fn render_pptx_presentation(slide_count: usize) -> String {
    let slide_ids = (1..=slide_count)
        .map(|index| {
            let id = 255 + index;
            format!(r#"<p:sldId id="{id}" r:id="rId{index}"/>"#)
        })
        .collect::<String>();
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><p:sldIdLst>{slide_ids}</p:sldIdLst><p:sldSz cx="9144000" cy="5143500"/></p:presentation>"#
    )
}

fn render_pptx_slide(slide: &PptxSlide, media: &[&ExportMedia]) -> String {
    let title = escape_xml(&slide.title);
    let body = slide
        .lines
        .iter()
        .filter(|line| !line.trim().is_empty())
        .map(|line| format!(r#"<a:p><a:r><a:t>{}</a:t></a:r></a:p>"#, escape_xml(line)))
        .collect::<String>();
    let pictures = media
        .iter()
        .enumerate()
        .map(|(index, item)| render_pptx_picture(item, index))
        .collect::<String>();
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><p:sld xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/><p:sp><p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>{title}</a:t></a:r></a:p>{body}</p:txBody></p:sp>{pictures}</p:spTree></p:cSld></p:sld>"#
    )
}

fn render_pptx_notes_slide(slide: &PptxSlide) -> String {
    let title = escape_xml(&format!("Notes: {}", slide.title));
    let notes = slide
        .notes
        .iter()
        .filter(|line| !line.trim().is_empty())
        .map(|line| format!(r#"<a:p><a:r><a:t>{}</a:t></a:r></a:p>"#, escape_xml(line)))
        .collect::<String>();
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><p:notes xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/><p:sp><p:nvSpPr><p:cNvPr id="2" name="Notes"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>{title}</a:t></a:r></a:p>{notes}</p:txBody></p:sp></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:notes>"#
    )
}

fn render_pptx_picture(item: &ExportMedia, index: usize) -> String {
    let shape_id = 20 + index;
    let y = 2_850_000 + (index as i64 * 1_000_000);
    format!(
        r#"<p:pic><p:nvPicPr><p:cNvPr id="{shape_id}" name="{}"/><p:cNvPicPr/><p:nvPr/></p:nvPicPr><p:blipFill><a:blip r:embed="{}"/><a:stretch><a:fillRect/></a:stretch></p:blipFill><p:spPr><a:xfrm><a:off x="457200" y="{y}"/><a:ext cx="3657600" cy="1371600"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr></p:pic>"#,
        escape_xml(&item.path),
        escape_xml(&item.relationship_id)
    )
}

fn pptx_slide_media<'a>(slide: &PptxSlide, media: &'a [ExportMedia]) -> Vec<&'a ExportMedia> {
    media
        .iter()
        .filter(|item| {
            slide.media_refs.iter().any(|media_ref| {
                media_ref.source == item.source && media_ref.source_file == item.source_file
            })
        })
        .collect()
}

fn export_css(
    brand_color: &str,
    watermark: &str,
    brand_font: &str,
    page_numbers: bool,
    layout_preset: &str,
    syntax_highlighting: bool,
    metadata: &Value,
) -> String {
    let page_counter_rule = if page_numbers {
        "@bottom-center{content:'Page ' counter(page) ' of ' counter(pages)}"
    } else {
        ""
    };
    let (body_margin, body_line_height, cover_min_height, heading_size, page_margin) =
        match layout_preset {
            "compact" => ("32px", "1.42", "72vh", "36px", "18mm"),
            "presentation" => ("64px", "1.7", "78vh", "54px", "20mm"),
            _ => ("48px", "1.55", "85vh", "44px", "24mm"),
        };
    let page_size = match layout_page_size(metadata).as_str() {
        "letter" => "Letter",
        "legal" => "Legal",
        _ => "A4",
    };
    let page_margin = match explicit_layout_margins(metadata).as_deref() {
        Some("narrow") | Some("compact") => "12mm",
        Some("wide") => "32mm",
        Some("normal") => "24mm",
        _ => page_margin,
    };
    let syntax_rules = if syntax_highlighting {
        ".syn-keyword{color:#7c3aed;font-weight:700}.syn-string{color:#047857}.syn-number{color:#b45309}.syn-comment{color:#64748b;font-style:italic}"
    } else {
        ""
    };
    format!(
        "body{{font-family:{};margin:{body_margin};color:#1f2937;line-height:{body_line_height}}}.running-header{{position:running(header);border-bottom:3px solid {brand_color};padding-bottom:8px;color:#475569}}.cover{{min-height:{cover_min_height};display:flex;flex-direction:column;justify-content:center;border-left:10px solid {brand_color};padding-left:32px;page-break-after:always}}.cover-logo{{max-width:160px;max-height:80px;object-fit:contain;margin-bottom:24px}}.cover h1{{font-size:{heading_size};margin:0 0 12px}}.subtitle{{font-size:22px;color:#475569}}.status{{display:inline-block;color:{brand_color};font-weight:700;text-transform:uppercase}}footer{{display:flex;justify-content:space-between;gap:16px;margin-top:40px;border-top:1px solid #cbd5e1;padding-top:12px;color:#475569}}h1,h2,h3{{color:#111827}}table{{border-collapse:collapse;width:100%}}td,th{{border:1px solid #cbd5e1;padding:6px 8px}}.citation{{color:{brand_color};font-weight:700}}.glossary-term{{border-bottom:1px dotted {brand_color};color:{brand_color};cursor:help}}.callout{{border-left:4px solid {brand_color};background:#eefaf4;padding:10px 12px;margin:14px 0}}.callout strong{{display:block;color:#0f5132;margin-bottom:4px}}.equation{{margin:18px 0}}.math-rendered{{font-family:Georgia,'Times New Roman',serif;font-size:1.08em}}.math-display{{padding:12px;border:1px solid #d8e0e8;background:#f8fafc;text-align:center}}.math-frac{{display:inline-grid;grid-template-rows:auto auto;vertical-align:middle;text-align:center}}.math-frac span:first-child{{border-bottom:1px solid currentColor}}.math-sqrt::before{{content:'√'}}.math-source-inline{{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0)}}.export-glossary,.export-comments,.export-provenance,.export-legal{{page-break-before:always;border-top:3px solid {brand_color};margin-top:40px;padding-top:16px}}.export-glossary dt{{font-weight:700;color:#111827}}.export-glossary dd{{margin:0 0 10px 0}}.export-comments li,.export-provenance li{{margin-bottom:12px}}.export-comments p,.export-provenance p{{margin:4px 0 0}}{syntax_rules}main::before{{content:'{}';position:fixed;inset:35% auto auto 20%;font-size:64px;color:rgba(0,0,0,.06);transform:rotate(-25deg);z-index:-1}}.page-break{{page-break-after:always}}@page{{size:{page_size};margin:{page_margin};@top-center{{content:element(header)}}{page_counter_rule}}}",
        escape_css(brand_font),
        escape_css(watermark)
    )
}
