use crate::{
    document_ast::{export_body_text_from_ast, DocumentBlock},
    escape_css, escape_html, escape_pdf, escape_xml, metadata_string, render_export_template,
    CompileResponse, ExportManifest,
};
use chrono::Utc;
use serde_json::Value;
use std::{
    fs,
    io::{Cursor, Write},
    path::PathBuf,
};
use zip::{write::SimpleFileOptions, CompressionMethod, ZipWriter};

pub(crate) fn render_full_html(response: &CompileResponse, options: &Value) -> String {
    let brand_color = options
        .get("brandColor")
        .and_then(Value::as_str)
        .or_else(|| {
            response
                .metadata
                .pointer("/brand/color")
                .and_then(Value::as_str)
        })
        .unwrap_or("#275DA8");
    let watermark = options
        .get("watermark")
        .and_then(Value::as_str)
        .unwrap_or("");
    let subtitle = metadata_string(&response.metadata, "subtitle");
    let author = metadata_string(&response.metadata, "author");
    let date = metadata_string(&response.metadata, "date");
    let version = metadata_string(&response.metadata, "version");
    let classification = metadata_string(&response.metadata, "classification");
    let brand = metadata_string(&response.metadata, "brand.name");
    let logo = export_logo(&response.metadata);
    let header_template = metadata_string(&response.metadata, "layout.header")
        .or_else(|| Some(response.semantic.title.clone()));
    let footer_template = metadata_string(&response.metadata, "layout.footer")
        .or_else(|| Some("Page {{page}} of {{pages}}".to_string()));
    let running_header = render_export_template(
        header_template.as_deref().unwrap_or(""),
        response,
        classification.as_deref().unwrap_or(""),
    );
    let running_footer = render_export_template(
        footer_template.as_deref().unwrap_or(""),
        response,
        classification.as_deref().unwrap_or(""),
    );
    let cover_meta = [author, date, version, classification, brand]
        .into_iter()
        .flatten()
        .map(|value| format!("<p>{}</p>", escape_html(&value)))
        .collect::<String>();
    let appendix_sections = html_appendix_sections(response, options);
    format!(
        "<!doctype html><html><head><meta charset=\"utf-8\"><title>{}</title><style>{}</style></head><body><div class=\"running-header\">{}</div><section class=\"cover\">{}<h1>{}</h1>{}<p class=\"status\">{}</p>{}</section><main>{}{}</main><footer><strong>{}</strong><span>{}</span><small>{}</small></footer></body></html>",
        escape_html(&response.semantic.title),
        export_css(brand_color, watermark),
        escape_html(&running_header),
        logo
            .as_ref()
            .map(|src| format!(
                "<img class=\"cover-logo\" src=\"{}\" alt=\"{} logo\"/>",
                escape_html(src),
                escape_html(&response.semantic.title)
            ))
            .unwrap_or_default(),
        escape_html(&response.semantic.title),
        subtitle
            .map(|value| format!("<p class=\"subtitle\">{}</p>", escape_html(&value)))
            .unwrap_or_default(),
        escape_html(&response.semantic.status),
        cover_meta,
        response.html,
        appendix_sections,
        escape_html(&running_footer),
        escape_html("Generated by NEditor"),
        escape_html(&Utc::now().to_rfc3339())
    )
}

pub(crate) fn render_pdf_bytes(response: &CompileResponse, options: &Value) -> Vec<u8> {
    let pages = build_pdf_pages(response, options);
    let mut objects = vec![
        String::new(),
        String::new(),
        "3 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n".to_string(),
    ];
    let mut page_ids = Vec::new();

    for page_lines in pages {
        let page_id = objects.len() + 1;
        let content_id = page_id + 1;
        page_ids.push(page_id);
        let stream = page_lines
            .iter()
            .take(60)
            .enumerate()
            .map(|(index, line)| {
                format!(
                    "BT /F1 10 Tf 50 {} Td ({}) Tj ET\n",
                    780 - (index as i32 * 12),
                    escape_pdf(line)
                )
            })
            .collect::<String>();
        objects.push(format!(
            "{page_id} 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents {content_id} 0 R >> endobj\n"
        ));
        objects.push(format!(
            "{content_id} 0 obj << /Length {} >> stream\n{}endstream endobj\n",
            stream.len(),
            stream
        ));
    }

    let kids = page_ids
        .iter()
        .map(|id| format!("{id} 0 R"))
        .collect::<Vec<_>>()
        .join(" ");
    objects[0] = "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n".to_string();
    objects[1] = format!(
        "2 0 obj << /Type /Pages /Kids [{kids}] /Count {} >> endobj\n",
        page_ids.len()
    );

    let mut pdf = b"%PDF-1.4\n".to_vec();
    let mut offsets = Vec::new();
    for object in &objects {
        offsets.push(pdf.len());
        pdf.extend_from_slice(object.as_bytes());
    }
    let xref = pdf.len();
    pdf.extend_from_slice(
        format!("xref\n0 {}\n0000000000 65535 f \n", objects.len() + 1).as_bytes(),
    );
    for offset in offsets {
        pdf.extend_from_slice(format!("{offset:010} 00000 n \n").as_bytes());
    }
    pdf.extend_from_slice(
        format!(
            "trailer << /Size {} /Root 1 0 R >>\nstartxref\n{}\n%%EOF\n",
            objects.len() + 1,
            xref
        )
        .as_bytes(),
    );
    pdf
}

pub(crate) fn render_docx_bytes(
    response: &CompileResponse,
    options_value: &Value,
) -> Result<Vec<u8>, String> {
    let mut cursor = Cursor::new(Vec::new());
    let mut zip = ZipWriter::new(&mut cursor);
    let options = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);
    zip.start_file("[Content_Types].xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_docx_content_types().as_bytes())
        .map_err(|err| err.to_string())?;
    zip.add_directory("_rels/", options)
        .map_err(|err| err.to_string())?;
    zip.start_file("_rels/.rels", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_root_relationships("word/document.xml").as_bytes())
        .map_err(|err| err.to_string())?;
    zip.add_directory("docProps/", options)
        .map_err(|err| err.to_string())?;
    zip.start_file("docProps/core.xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_core_properties(response).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.add_directory("word/", options)
        .map_err(|err| err.to_string())?;
    zip.add_directory("word/_rels/", options)
        .map_err(|err| err.to_string())?;
    zip.start_file("word/_rels/document.xml.rels", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_docx_document_relationships().as_bytes())
        .map_err(|err| err.to_string())?;
    zip.start_file("word/header1.xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_docx_header(response, options_value).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.start_file("word/footer1.xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_docx_footer(response, options_value).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.start_file("word/document.xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_docx_document(response, options_value).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.finish().map_err(|err| err.to_string())?;
    Ok(cursor.into_inner())
}

pub(crate) fn render_pptx_bytes(
    response: &CompileResponse,
    options_value: &Value,
) -> Result<Vec<u8>, String> {
    let slides = build_pptx_slides(response, options_value);
    let mut cursor = Cursor::new(Vec::new());
    let mut zip = ZipWriter::new(&mut cursor);
    let options = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);
    zip.start_file("[Content_Types].xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_pptx_content_types(slides.len()).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.add_directory("_rels/", options)
        .map_err(|err| err.to_string())?;
    zip.start_file("_rels/.rels", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_root_relationships("ppt/presentation.xml").as_bytes())
        .map_err(|err| err.to_string())?;
    zip.add_directory("docProps/", options)
        .map_err(|err| err.to_string())?;
    zip.start_file("docProps/core.xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_core_properties(response).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.add_directory("ppt/_rels/", options)
        .map_err(|err| err.to_string())?;
    zip.start_file("ppt/_rels/presentation.xml.rels", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_pptx_relationships(slides.len()).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.add_directory("ppt/slides/", options)
        .map_err(|err| err.to_string())?;
    zip.start_file("ppt/presentation.xml", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(render_pptx_presentation(slides.len()).as_bytes())
        .map_err(|err| err.to_string())?;
    for (index, slide) in slides.iter().enumerate() {
        zip.start_file(format!("ppt/slides/slide{}.xml", index + 1), options)
            .map_err(|err| err.to_string())?;
        zip.write_all(render_pptx_slide(slide).as_bytes())
            .map_err(|err| err.to_string())?;
    }
    zip.finish().map_err(|err| err.to_string())?;
    Ok(cursor.into_inner())
}

pub(crate) fn render_markdown_bundle_bytes(
    response: &CompileResponse,
    manifest: &ExportManifest,
) -> Result<Vec<u8>, String> {
    let mut cursor = Cursor::new(Vec::new());
    let mut zip = ZipWriter::new(&mut cursor);
    let options = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);
    zip.start_file("document.md", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(response.compiled_markdown.as_bytes())
        .map_err(|err| err.to_string())?;
    zip.start_file("document.txt", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(export_text(response, &manifest.export_options).as_bytes())
        .map_err(|err| err.to_string())?;
    zip.start_file("manifest.json", options)
        .map_err(|err| err.to_string())?;
    zip.write_all(
        serde_json::to_string_pretty(manifest)
            .map_err(|err| err.to_string())?
            .as_bytes(),
    )
    .map_err(|err| err.to_string())?;
    for included in &manifest.included_files {
        if let Ok(bytes) = fs::read(&included.path) {
            let bundle_path = format!("includes/{}", safe_bundle_path(&included.path));
            zip.start_file(bundle_path, options)
                .map_err(|err| err.to_string())?;
            zip.write_all(&bytes).map_err(|err| err.to_string())?;
        }
    }
    zip.finish().map_err(|err| err.to_string())?;
    Ok(cursor.into_inner())
}

fn safe_bundle_path(path: &str) -> String {
    PathBuf::from(path)
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("include.md")
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || matches!(ch, '.' | '-' | '_') {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn render_docx_content_types() -> String {
    r#"<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/header1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/><Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/></Types>"#.to_string()
}

fn render_root_relationships(office_document_target: &str) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="{}"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/></Relationships>"#,
        escape_xml(office_document_target)
    )
}

fn render_docx_document_relationships() -> String {
    r#"<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdHeader1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Target="header1.xml"/><Relationship Id="rIdFooter1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/></Relationships>"#.to_string()
}

fn render_core_properties(response: &CompileResponse) -> String {
    let author = metadata_string(&response.metadata, "author")
        .or_else(|| metadata_string(&response.metadata, "approvedBy"))
        .unwrap_or_else(|| "NEditor".to_string());
    let version = metadata_string(&response.metadata, "version").unwrap_or_default();
    let classification = metadata_string(&response.metadata, "classification").unwrap_or_default();
    let keywords = [
        response.semantic.status.as_str(),
        version.as_str(),
        classification.as_str(),
    ]
    .into_iter()
    .filter(|value| !value.is_empty())
    .collect::<Vec<_>>()
    .join("; ");
    let description = format!(
        "Status: {}; Version: {}",
        response.semantic.status,
        if version.is_empty() {
            "unversioned"
        } else {
            version.as_str()
        }
    );
    let timestamp = Utc::now().to_rfc3339();
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>{}</dc:title><dc:creator>{}</dc:creator><dc:description>{}</dc:description><cp:keywords>{}</cp:keywords><cp:category>{}</cp:category><cp:lastModifiedBy>NEditor</cp:lastModifiedBy><dcterms:created xsi:type="dcterms:W3CDTF">{}</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">{}</dcterms:modified></cp:coreProperties>"#,
        escape_xml(&response.semantic.title),
        escape_xml(&author),
        escape_xml(&description),
        escape_xml(&keywords),
        escape_xml(&response.semantic.status),
        escape_xml(&timestamp),
        escape_xml(&timestamp)
    )
}

pub(crate) fn export_text(response: &CompileResponse, options: &Value) -> String {
    let mut lines = export_metadata_lines(response, options);
    lines.push(String::new());
    lines.push(export_body_text_from_ast(&response.document_ast));
    lines.extend(appendix_export_lines(response, options));
    lines.join("\n")
}

fn export_metadata_lines(response: &CompileResponse, options: &Value) -> Vec<String> {
    let (header, footer) = export_header_footer(response, options);
    let watermark = options
        .get("watermark")
        .and_then(Value::as_str)
        .unwrap_or("");
    let mut lines = vec![
        format!("Cover: {}", response.semantic.title),
        format!("Status: {}", response.semantic.status),
        format!("Header: {header}"),
        format!("Footer: {footer}"),
        "Page 1 of 1".to_string(),
    ];
    for path in ["subtitle", "author", "date", "version", "brand.name"] {
        if let Some(value) = metadata_string(&response.metadata, path) {
            lines.push(value);
        }
    }
    if let Some(logo) = export_logo(&response.metadata) {
        lines.push(format!("Logo: {logo}"));
    }
    if !watermark.is_empty() {
        lines.push(format!("Watermark: {watermark}"));
    }
    lines
}

fn export_logo(metadata: &Value) -> Option<String> {
    metadata_string(metadata, "brand.logo")
        .or_else(|| metadata_string(metadata, "layout.logo"))
        .or_else(|| metadata_string(metadata, "logo"))
        .filter(|value| !value.trim().is_empty())
}

fn export_header_footer(response: &CompileResponse, _options: &Value) -> (String, String) {
    let classification = metadata_string(&response.metadata, "classification").unwrap_or_default();
    let header = metadata_string(&response.metadata, "layout.header")
        .map(|template| render_export_template(&template, response, &classification))
        .unwrap_or_else(|| response.semantic.title.clone());
    let footer = metadata_string(&response.metadata, "layout.footer")
        .map(|template| render_export_template(&template, response, &classification))
        .unwrap_or_else(|| "Page 1 of 1".to_string());
    (header, footer)
}

fn include_glossary(options: &Value) -> bool {
    options
        .get("includeGlossary")
        .and_then(Value::as_bool)
        .unwrap_or(false)
}

fn include_comments(options: &Value) -> bool {
    options
        .get("includeComments")
        .and_then(Value::as_bool)
        .unwrap_or(false)
}

fn include_provenance(options: &Value) -> bool {
    options
        .get("includeProvenance")
        .and_then(Value::as_bool)
        .unwrap_or(false)
}

fn appendix_export_lines(response: &CompileResponse, options: &Value) -> Vec<String> {
    let mut lines = glossary_export_lines(response, options);
    lines.extend(comment_export_lines(response, options));
    lines.extend(provenance_export_lines(response, options));
    lines
}

fn glossary_export_lines(response: &CompileResponse, options: &Value) -> Vec<String> {
    if !include_glossary(options) || response.semantic.glossary.is_empty() {
        return Vec::new();
    }
    let mut lines = vec![String::new(), "Glossary".to_string()];
    lines.extend(
        response
            .semantic
            .glossary
            .iter()
            .map(|(term, definition)| format!("{term}: {definition}")),
    );
    lines
}

fn comment_export_lines(response: &CompileResponse, options: &Value) -> Vec<String> {
    if !include_comments(options) || response.semantic.comments.is_empty() {
        return Vec::new();
    }
    let mut lines = vec![String::new(), "Review Comments".to_string()];
    lines.extend(response.semantic.comments.iter().map(|comment| {
        let created_at = if comment.created_at.is_empty() {
            "undated"
        } else {
            comment.created_at.as_str()
        };
        let author = if comment.author.is_empty() {
            "local"
        } else {
            comment.author.as_str()
        };
        format!(
            "Line {} [{}] {} at {}: {}",
            comment.line, comment.state, author, created_at, comment.text
        )
    }));
    lines
}

fn provenance_export_lines(response: &CompileResponse, options: &Value) -> Vec<String> {
    if !include_provenance(options) || response.semantic.ai_sources.is_empty() {
        return Vec::new();
    }
    let mut lines = vec![String::new(), "AI Provenance".to_string()];
    lines.extend(response.semantic.ai_sources.iter().map(|source| {
        let provider = empty_as(source.provider.as_str(), "unknown provider");
        let model = empty_as(source.model.as_str(), "unknown model");
        let date = empty_as(source.date.as_str(), "undated");
        let reviewer = empty_as(source.reviewed_by.as_str(), "unreviewed");
        format!(
            "{provider} / {model} on {date}; status: {}; reviewed by: {reviewer}",
            source.status
        )
    }));
    lines
}

fn empty_as<'a>(value: &'a str, fallback: &'a str) -> &'a str {
    if value.is_empty() {
        fallback
    } else {
        value
    }
}

fn html_appendix_sections(response: &CompileResponse, options: &Value) -> String {
    [
        html_glossary_section(response, options),
        html_comments_section(response, options),
        html_provenance_section(response, options),
    ]
    .join("")
}

fn html_glossary_section(response: &CompileResponse, options: &Value) -> String {
    if !include_glossary(options) || response.semantic.glossary.is_empty() {
        return String::new();
    }
    let entries = response
        .semantic
        .glossary
        .iter()
        .map(|(term, definition)| {
            format!(
                "<dt>{}</dt><dd>{}</dd>",
                escape_html(term),
                escape_html(definition)
            )
        })
        .collect::<String>();
    format!("<section class=\"export-glossary\"><h2>Glossary</h2><dl>{entries}</dl></section>")
}

fn html_comments_section(response: &CompileResponse, options: &Value) -> String {
    if !include_comments(options) || response.semantic.comments.is_empty() {
        return String::new();
    }
    let entries = response
        .semantic
        .comments
        .iter()
        .map(|comment| {
            let created_at = empty_as(comment.created_at.as_str(), "undated");
            let author = empty_as(comment.author.as_str(), "local");
            format!(
                "<li><strong>Line {}</strong> <span>{}</span> <em>{} at {}</em><p>{}</p></li>",
                comment.line,
                escape_html(&comment.state),
                escape_html(author),
                escape_html(created_at),
                escape_html(&comment.text)
            )
        })
        .collect::<String>();
    format!(
        "<section class=\"export-comments\"><h2>Review Comments</h2><ol>{entries}</ol></section>"
    )
}

fn html_provenance_section(response: &CompileResponse, options: &Value) -> String {
    if !include_provenance(options) || response.semantic.ai_sources.is_empty() {
        return String::new();
    }
    let entries = response
        .semantic
        .ai_sources
        .iter()
        .map(|source| {
            format!(
                "<li><strong>{}</strong> <span>{}</span><p>{}; reviewed by {}; {}</p></li>",
                escape_html(empty_as(source.provider.as_str(), "unknown provider")),
                escape_html(empty_as(source.model.as_str(), "unknown model")),
                escape_html(empty_as(source.date.as_str(), "undated")),
                escape_html(empty_as(source.reviewed_by.as_str(), "unreviewed")),
                escape_html(&source.status)
            )
        })
        .collect::<String>();
    format!(
        "<section class=\"export-provenance\"><h2>AI Provenance</h2><ol>{entries}</ol></section>"
    )
}

fn render_docx_document(response: &CompileResponse, options: &Value) -> String {
    let mut body = String::new();
    for line in export_metadata_lines(response, options) {
        body.push_str(&docx_paragraph(&line));
    }
    body.push_str(&docx_page_break());
    for block in &response.document_ast.blocks {
        body.push_str(&render_docx_block(block));
    }
    for line in appendix_export_lines(response, options) {
        if matches!(
            line.as_str(),
            "Glossary" | "Review Comments" | "AI Provenance"
        ) {
            body.push_str(&docx_heading(1, &line));
        } else {
            body.push_str(&docx_paragraph(&line));
        }
    }
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><w:body>{body}<w:sectPr><w:headerReference w:type="default" r:id="rIdHeader1"/><w:footerReference w:type="default" r:id="rIdFooter1"/><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>"#
    )
}

fn render_docx_header(response: &CompileResponse, options: &Value) -> String {
    let (header, _) = export_header_footer(response, options);
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><w:hdr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">{}</w:hdr>"#,
        docx_paragraph(&header)
    )
}

fn render_docx_footer(response: &CompileResponse, options: &Value) -> String {
    let (_, footer) = export_header_footer(response, options);
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><w:ftr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">{}</w:ftr>"#,
        docx_paragraph(&footer)
    )
}

fn render_docx_block(block: &DocumentBlock) -> String {
    match block {
        DocumentBlock::Heading { level, text, .. } => docx_heading(*level, text),
        DocumentBlock::Paragraph { text, .. } => docx_paragraph(text),
        DocumentBlock::Table { headers, rows, .. } => docx_table(headers, rows),
        DocumentBlock::Figure {
            id,
            src,
            alt,
            caption,
            ..
        } => docx_paragraph(&figure_export_line(id, src, alt, caption)),
        DocumentBlock::Equation {
            id, caption, text, ..
        } => docx_paragraph(&equation_export_line(id, text, caption)),
        DocumentBlock::Layout { directive, .. } if directive == "page-break" => docx_page_break(),
        DocumentBlock::Layout {
            directive, options, ..
        } if directive == "section-break" || layout_columns(options).is_some() => {
            docx_section_break(options)
        }
        DocumentBlock::Layout {
            directive, options, ..
        } => docx_paragraph(&format!("Layout: {directive} {options}").trim().to_string()),
        DocumentBlock::Callout {
            callout_type,
            title,
            text,
            ..
        } => docx_paragraph(&callout_export_line(callout_type, title, text)),
        DocumentBlock::RawHtml { html, .. } => docx_paragraph(html),
    }
}

fn docx_heading(level: usize, text: &str) -> String {
    let style = format!("Heading{}", level.clamp(1, 6));
    format!(
        r#"<w:p><w:pPr><w:pStyle w:val="{style}"/></w:pPr><w:r><w:t>{}</w:t></w:r></w:p>"#,
        escape_xml(text)
    )
}

fn docx_paragraph(text: &str) -> String {
    format!(r#"<w:p><w:r><w:t>{}</w:t></w:r></w:p>"#, escape_xml(text))
}

fn docx_page_break() -> String {
    r#"<w:p><w:r><w:br w:type="page"/></w:r></w:p>"#.to_string()
}

fn docx_section_break(options: &str) -> String {
    let columns = layout_columns(options).unwrap_or(1);
    format!(
        r#"<w:p><w:pPr><w:sectPr><w:cols w:num="{columns}" w:space="720"/></w:sectPr></w:pPr></w:p>"#
    )
}

fn docx_table(headers: &[String], rows: &[Vec<String>]) -> String {
    let mut table = String::from(
        r#"<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/><w:tblW w:w="0" w:type="auto"/></w:tblPr>"#,
    );
    table.push_str(&docx_table_row(headers));
    for row in rows {
        table.push_str(&docx_table_row(row));
    }
    table.push_str("</w:tbl>");
    table
}

fn docx_table_row(cells: &[String]) -> String {
    let cells = cells.iter().map(|cell| docx_cell(cell)).collect::<String>();
    format!("<w:tr>{cells}</w:tr>")
}

fn docx_cell(text: &str) -> String {
    format!(
        r#"<w:tc><w:tcPr><w:tcW w:w="2400" w:type="dxa"/></w:tcPr>{}</w:tc>"#,
        docx_paragraph(text)
    )
}

fn build_pdf_pages(response: &CompileResponse, options: &Value) -> Vec<Vec<String>> {
    let mut pages = vec![export_metadata_lines(response, options)];
    let mut current = Vec::new();
    for block in &response.document_ast.blocks {
        match block {
            DocumentBlock::Layout { directive, .. } if directive == "page-break" => {
                if !current.is_empty() {
                    pages.push(current);
                    current = Vec::new();
                }
            }
            DocumentBlock::Layout {
                directive, options, ..
            } if directive == "section-break" => {
                if !current.is_empty() {
                    pages.push(current);
                    current = Vec::new();
                }
                current.extend(layout_export_lines(directive, options));
            }
            _ => current.extend(block_export_lines(block)),
        }
    }
    if !current.is_empty() {
        pages.push(current);
    }
    for appendix in appendix_pages(response, options) {
        pages.push(appendix);
    }
    pages
}

fn appendix_pages(response: &CompileResponse, options: &Value) -> Vec<Vec<String>> {
    [
        glossary_export_lines(response, options),
        comment_export_lines(response, options),
        provenance_export_lines(response, options),
    ]
    .into_iter()
    .filter(|lines| !lines.is_empty())
    .collect()
}

#[derive(Debug)]
struct PptxSlide {
    title: String,
    lines: Vec<String>,
}

fn build_pptx_slides(response: &CompileResponse, options: &Value) -> Vec<PptxSlide> {
    let mut slides = vec![PptxSlide {
        title: response.semantic.title.clone(),
        lines: export_metadata_lines(response, options)
            .into_iter()
            .filter(|line| !line.starts_with("Cover: "))
            .collect(),
    }];
    let include_agenda = include_pptx_agenda(response, options);
    if include_agenda {
        let lines = response
            .semantic
            .outline
            .iter()
            .filter(|heading| heading.level <= 2)
            .map(|heading| {
                format!(
                    "{}{}",
                    "  ".repeat(heading.level.saturating_sub(1)),
                    heading.text
                )
            })
            .collect::<Vec<_>>();
        if !lines.is_empty() {
            slides.push(PptxSlide {
                title: "Agenda".to_string(),
                lines,
            });
        }
    }
    let mut current: Option<PptxSlide> = None;
    let mut skip_next_toc_body = false;

    for block in &response.document_ast.blocks {
        if skip_next_toc_body {
            skip_next_toc_body = false;
            if is_generated_toc_body(block) {
                continue;
            }
        }
        if include_agenda && is_generated_toc_heading(block) {
            skip_next_toc_body = true;
            continue;
        }
        match block {
            DocumentBlock::Heading { level, text, .. } if *level <= 2 => {
                if let Some(slide) = current.take() {
                    if !slide.lines.is_empty() || slide.title != "Continued" {
                        slides.push(slide);
                    }
                }
                current = Some(PptxSlide {
                    title: text.clone(),
                    lines: Vec::new(),
                });
            }
            DocumentBlock::Layout { directive, .. } if directive == "page-break" => {
                if let Some(slide) = current.take() {
                    slides.push(slide);
                }
                current = Some(PptxSlide {
                    title: "Continued".to_string(),
                    lines: Vec::new(),
                });
            }
            DocumentBlock::Layout {
                directive, options, ..
            } if directive == "section-break" => {
                if let Some(slide) = current.take() {
                    if !slide.lines.is_empty() || slide.title != "Continued" {
                        slides.push(slide);
                    }
                }
                current = Some(PptxSlide {
                    title: "Section".to_string(),
                    lines: layout_export_lines(directive, options),
                });
            }
            _ => {
                if current.is_none() {
                    current = Some(PptxSlide {
                        title: "Document".to_string(),
                        lines: Vec::new(),
                    });
                }
                if let Some(slide) = current.as_mut() {
                    slide.lines.extend(block_export_lines(block));
                }
            }
        }
    }

    if let Some(slide) = current {
        if !slide.lines.is_empty() || slide.title != "Continued" {
            slides.push(slide);
        }
    }
    for appendix in appendix_pages(response, options) {
        let title = appendix
            .iter()
            .find(|line| {
                matches!(
                    line.as_str(),
                    "Glossary" | "Review Comments" | "AI Provenance"
                )
            })
            .cloned()
            .unwrap_or_else(|| "Appendix".to_string());
        slides.push(PptxSlide {
            title,
            lines: appendix
                .into_iter()
                .filter(|line| !line.is_empty())
                .filter(|line| {
                    !matches!(
                        line.as_str(),
                        "Glossary" | "Review Comments" | "AI Provenance"
                    )
                })
                .collect(),
        });
    }
    slides
        .into_iter()
        .map(|mut slide| {
            if slide.lines.is_empty() {
                slide.lines.push("No body content".to_string());
            }
            slide.lines.truncate(14);
            slide
        })
        .collect()
}

fn include_pptx_agenda(response: &CompileResponse, options: &Value) -> bool {
    options
        .get("includeAgenda")
        .and_then(Value::as_bool)
        .or_else(|| response.metadata.get("toc").and_then(Value::as_bool))
        .unwrap_or(false)
}

fn is_generated_toc_heading(block: &DocumentBlock) -> bool {
    matches!(
        block,
        DocumentBlock::Heading { level, text, .. }
            if *level == 2 && text == "Table of Contents"
    )
}

fn is_generated_toc_body(block: &DocumentBlock) -> bool {
    matches!(
        block,
        DocumentBlock::Paragraph { text, .. }
            if text.trim_start().starts_with("- [") && text.contains("](#")
    )
}

fn block_export_lines(block: &DocumentBlock) -> Vec<String> {
    match block {
        DocumentBlock::Heading { level, text, .. } => {
            vec![format!("{} {text}", "#".repeat(*level))]
        }
        DocumentBlock::Paragraph { text, .. } => vec![text.clone()],
        DocumentBlock::Table { headers, rows, .. } => {
            let mut lines = vec![format!("Table: {}", headers.join(" | "))];
            lines.extend(rows.iter().map(|row| row.join(" | ")));
            lines
        }
        DocumentBlock::Figure {
            id,
            src,
            alt,
            caption,
            ..
        } => vec![figure_export_line(id, src, alt, caption)],
        DocumentBlock::Equation {
            id, caption, text, ..
        } => vec![equation_export_line(id, text, caption)],
        DocumentBlock::Layout {
            directive, options, ..
        } => layout_export_lines(directive, options),
        DocumentBlock::Callout {
            callout_type,
            title,
            text,
            ..
        } => vec![callout_export_line(callout_type, title, text)],
        DocumentBlock::RawHtml { html, .. } => vec![html.clone()],
    }
}

fn layout_export_lines(directive: &str, options: &str) -> Vec<String> {
    let summary = layout_summary(options);
    let label = match directive {
        "section-break" => "Section break",
        "layout" => "Layout",
        "page-break" => "Page break",
        _ => "Layout directive",
    };
    vec![format!("{label}{summary}")]
}

fn layout_summary(options: &str) -> String {
    let mut parts = Vec::new();
    if let Some(columns) = layout_columns(options) {
        parts.push(format!("columns={columns}"));
    }
    if parts.is_empty() {
        let trimmed = options.trim();
        if trimmed.is_empty() {
            String::new()
        } else {
            format!(": {trimmed}")
        }
    } else {
        format!(": {}", parts.join(", "))
    }
}

fn layout_columns(options: &str) -> Option<usize> {
    for line in options.lines() {
        if let Some((key, value)) = line.split_once(':') {
            if key.trim() == "columns" {
                return parse_layout_columns(value);
            }
        }
    }
    for part in options.split_whitespace() {
        if let Some((key, value)) = part.split_once('=') {
            if key.trim() == "columns" {
                return parse_layout_columns(value);
            }
        }
    }
    None
}

fn parse_layout_columns(value: &str) -> Option<usize> {
    let columns = value.trim().trim_matches('"').parse::<usize>().ok()?;
    (columns > 0).then_some(columns)
}

fn callout_export_line(callout_type: &str, title: &str, text: &str) -> String {
    let mut parts = vec![format!("Callout: {callout_type}")];
    if !title.is_empty() {
        parts.push(title.to_string());
    }
    if !text.is_empty() {
        parts.push(text.to_string());
    }
    parts.join(": ")
}

fn figure_export_line(
    id: &Option<String>,
    src: &Option<String>,
    alt: &Option<String>,
    caption: &Option<String>,
) -> String {
    let mut parts = vec!["Figure".to_string()];
    if let Some(id) = id {
        parts.push(id.clone());
    }
    if let Some(caption) = caption {
        parts.push(caption.clone());
    }
    if let Some(alt) = alt {
        parts.push(alt.clone());
    }
    if let Some(src) = src {
        parts.push(format!("({src})"));
    }
    parts.join(": ")
}

fn equation_export_line(id: &Option<String>, text: &str, caption: &Option<String>) -> String {
    let mut parts = vec!["Equation".to_string()];
    if let Some(id) = id {
        parts.push(id.clone());
    }
    if !text.is_empty() {
        parts.push(text.to_string());
    }
    if let Some(caption) = caption {
        parts.push(caption.clone());
    }
    parts.join(": ")
}

fn render_pptx_content_types(slide_count: usize) -> String {
    let slide_overrides = (1..=slide_count)
        .map(|index| format!(r#"<Override PartName="/ppt/slides/slide{index}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>"#))
        .collect::<String>();
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>{slide_overrides}</Types>"#
    )
}

fn render_pptx_relationships(slide_count: usize) -> String {
    let relationships = (1..=slide_count)
        .map(|index| format!(r#"<Relationship Id="rId{index}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide{index}.xml"/>"#))
        .collect::<String>();
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">{relationships}</Relationships>"#
    )
}

fn render_pptx_presentation(slide_count: usize) -> String {
    let slide_ids = (1..=slide_count)
        .map(|index| {
            let id = 255 + index;
            format!(r#"<p:sldId id="{id}" r:id="rId{index}"/>"#)
        })
        .collect::<String>();
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><p:sldIdLst>{slide_ids}</p:sldIdLst><p:sldSz cx="9144000" cy="5143500"/></p:presentation>"#
    )
}

fn render_pptx_slide(slide: &PptxSlide) -> String {
    let title = escape_xml(&slide.title);
    let body = slide
        .lines
        .iter()
        .filter(|line| !line.trim().is_empty())
        .map(|line| format!(r#"<a:p><a:r><a:t>{}</a:t></a:r></a:p>"#, escape_xml(line)))
        .collect::<String>();
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?><p:sld xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/><p:sp><p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>{title}</a:t></a:r></a:p>{body}</p:txBody></p:sp></p:spTree></p:cSld></p:sld>"#
    )
}

fn export_css(brand_color: &str, watermark: &str) -> String {
    format!(
        "body{{font-family:Inter,Arial,sans-serif;margin:48px;color:#1f2937;line-height:1.55}}.running-header{{position:running(header);border-bottom:3px solid {brand_color};padding-bottom:8px;color:#475569}}.cover{{min-height:85vh;display:flex;flex-direction:column;justify-content:center;border-left:10px solid {brand_color};padding-left:32px;page-break-after:always}}.cover-logo{{max-width:160px;max-height:80px;object-fit:contain;margin-bottom:24px}}.cover h1{{font-size:44px;margin:0 0 12px}}.subtitle{{font-size:22px;color:#475569}}.status{{display:inline-block;color:{brand_color};font-weight:700;text-transform:uppercase}}footer{{display:flex;justify-content:space-between;gap:16px;margin-top:40px;border-top:1px solid #cbd5e1;padding-top:12px;color:#475569}}h1,h2,h3{{color:#111827}}table{{border-collapse:collapse;width:100%}}td,th{{border:1px solid #cbd5e1;padding:6px 8px}}.citation{{color:{brand_color};font-weight:700}}.glossary-term{{border-bottom:1px dotted {brand_color};color:{brand_color};cursor:help}}.callout{{border-left:4px solid {brand_color};background:#eefaf4;padding:10px 12px;margin:14px 0}}.callout strong{{display:block;color:#0f5132;margin-bottom:4px}}.export-glossary,.export-comments,.export-provenance{{page-break-before:always;border-top:3px solid {brand_color};margin-top:40px;padding-top:16px}}.export-glossary dt{{font-weight:700;color:#111827}}.export-glossary dd{{margin:0 0 10px 0}}.export-comments li,.export-provenance li{{margin-bottom:12px}}.export-comments p,.export-provenance p{{margin:4px 0 0}}main::before{{content:'{}';position:fixed;inset:35% auto auto 20%;font-size:64px;color:rgba(0,0,0,.06);transform:rotate(-25deg);z-index:-1}}.page-break{{page-break-after:always}}@page{{margin:24mm;@top-center{{content:element(header)}}@bottom-center{{content:'Page ' counter(page) ' of ' counter(pages)}}}}",
        escape_css(watermark)
    )
}
