use super::*;

pub(crate) fn render_full_html(response: &CompileResponse, options: &Value) -> String {
    let brand_color = options
        .get("brandColor")
        .and_then(Value::as_str)
        .or_else(|| {
            response
                .metadata
                .pointer("/brand/color")
                .and_then(Value::as_str)
        })
        .unwrap_or("#275DA8");
    let watermark = options
        .get("watermark")
        .and_then(Value::as_str)
        .unwrap_or("");
    let brand_font = metadata_string(&response.metadata, "brand.font")
        .filter(|value| !value.trim().is_empty())
        .unwrap_or_else(|| "Inter,Arial,sans-serif".to_string());
    let subtitle = metadata_string(&response.metadata, "subtitle");
    let author = metadata_string(&response.metadata, "author");
    let date = metadata_string(&response.metadata, "date");
    let version = metadata_string(&response.metadata, "version");
    let classification = metadata_string(&response.metadata, "classification");
    let brand = metadata_string(&response.metadata, "brand.name");
    let audience =
        target_persona_summary(&response.metadata).map(|value| format!("Audience: {value}"));
    let logo = export_logo(&response.metadata);
    let header_template = metadata_string(&response.metadata, "layout.header")
        .or_else(|| Some(response.semantic.title.clone()));
    let footer_template = metadata_string(&response.metadata, "layout.footer").or_else(|| {
        include_page_numbers(options).then(|| "Page {{page}} of {{pages}}".to_string())
    });
    let running_header = render_export_template(
        header_template.as_deref().unwrap_or(""),
        response,
        classification.as_deref().unwrap_or(""),
    );
    let running_footer = render_export_template(
        footer_template.as_deref().unwrap_or(""),
        response,
        classification.as_deref().unwrap_or(""),
    );
    let language = html_document_language(&response.metadata, options);
    let head_metadata = html_head_metadata(
        response,
        options,
        &subtitle,
        &author,
        &date,
        &version,
        &classification,
    );
    let cover_meta = [author, date, version, classification, brand, audience]
        .into_iter()
        .flatten()
        .map(|value| format!("<p>{}</p>", escape_html(&value)))
        .collect::<String>();
    let appendix_sections = html_appendix_sections(response, options);
    let style_tag = if include_styles(options) {
        format!(
            "<style>{}</style>",
            export_css(
                brand_color,
                watermark,
                &brand_font,
                include_page_numbers(options),
                layout_preset(options),
                include_syntax_highlighting(options),
                &response.metadata,
            )
        )
    } else {
        String::new()
    };
    let cover_section = if include_cover_page(options) {
        format!(
            "<section class=\"cover\">{}<h1>{}</h1>{}<p class=\"status\">{}</p>{}</section>",
            logo.as_ref()
                .map(|src| format!(
                    "<img class=\"cover-logo\" src=\"{}\" alt=\"{} logo\"/>",
                    escape_html(src),
                    escape_html(&response.semantic.title)
                ))
                .unwrap_or_default(),
            escape_html(&response.semantic.title),
            subtitle
                .map(|value| format!("<p class=\"subtitle\">{}</p>", escape_html(&value)))
                .unwrap_or_default(),
            escape_html(&response.semantic.status),
            cover_meta
        )
    } else {
        String::new()
    };
    let body_html = if include_syntax_highlighting(options) {
        highlight_code_blocks(&response.html)
    } else {
        response.html.clone()
    };
    format!(
        "<!doctype html><html lang=\"{}\"><head><meta charset=\"utf-8\">{}<title>{}</title>{}</head><body><div class=\"running-header\">{}</div>{}<main>{}{}</main><footer><strong>{}</strong><span>{}</span><small>{}</small></footer></body></html>",
        escape_html(&language),
        head_metadata,
        escape_html(&response.semantic.title),
        style_tag,
        escape_html(&running_header),
        cover_section,
        body_html,
        appendix_sections,
        escape_html(&running_footer),
        escape_html("Generated by NEditor"),
        escape_html(&Utc::now().to_rfc3339())
    )
}

fn html_document_language(metadata: &Value, options: &Value) -> String {
    [
        options
            .get("htmlLanguage")
            .and_then(Value::as_str)
            .map(str::to_string),
        options
            .get("language")
            .and_then(Value::as_str)
            .map(str::to_string),
        metadata_string(metadata, "htmlLanguage"),
        metadata_string(metadata, "language"),
        metadata_string(metadata, "lang"),
        metadata_string(metadata, "locale"),
    ]
    .into_iter()
    .flatten()
    .find_map(|value| normalize_html_language(&value))
    .unwrap_or_else(|| "en".to_string())
}

fn normalize_html_language(value: &str) -> Option<String> {
    let normalized = value.trim().replace('_', "-");
    if normalized.is_empty()
        || normalized.len() > 35
        || !normalized
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || ch == '-')
    {
        return None;
    }
    Some(normalized)
}

fn html_head_metadata(
    response: &CompileResponse,
    options: &Value,
    subtitle: &Option<String>,
    author: &Option<String>,
    date: &Option<String>,
    version: &Option<String>,
    classification: &Option<String>,
) -> String {
    let mut tags = vec![
        r#"<meta name="viewport" content="width=device-width, initial-scale=1">"#.to_string(),
        r#"<meta name="generator" content="NEditor">"#.to_string(),
        html_meta_tag("neditor-status", &response.semantic.status),
        html_meta_tag("neditor-source-hash", &response.export_manifest.source_hash),
    ];
    if let Some(description) = options
        .get("htmlDescription")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_string)
        .or_else(|| metadata_string(&response.metadata, "description"))
        .or_else(|| metadata_string(&response.metadata, "summary"))
        .or_else(|| subtitle.clone())
        .filter(|value| !value.trim().is_empty())
    {
        tags.push(html_meta_tag("description", &description));
    }
    if let Some(value) = author
        .clone()
        .or_else(|| metadata_string(&response.metadata, "approvedBy"))
        .filter(|value| !value.trim().is_empty())
    {
        tags.push(html_meta_tag("author", &value));
    }
    for (name, value) in [
        ("neditor-date", date),
        ("neditor-version", version),
        ("neditor-classification", classification),
        (
            "neditor-delivery-model",
            &metadata_string(&response.metadata, "positioning.model"),
        ),
        (
            "neditor-source-of-truth",
            &metadata_string(&response.metadata, "positioning.sourceOfTruth"),
        ),
    ] {
        if let Some(value) = value.as_ref().filter(|value| !value.trim().is_empty()) {
            tags.push(html_meta_tag(name, value));
        }
    }
    if let Some(canonical) = options
        .get("canonicalUrl")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_string)
        .or_else(|| metadata_string(&response.metadata, "canonicalUrl"))
        .or_else(|| metadata_string(&response.metadata, "canonical_url"))
        .filter(|value| !value.trim().is_empty())
    {
        tags.push(format!(
            r#"<link rel="canonical" href="{}">"#,
            escape_html(&canonical)
        ));
    }
    tags.join("")
}

fn html_meta_tag(name: &str, content: &str) -> String {
    format!(
        r#"<meta name="{}" content="{}">"#,
        escape_html(name),
        escape_html(content)
    )
}

fn highlight_code_blocks(html: &str) -> String {
    let mut output = String::with_capacity(html.len());
    let mut rest = html;
    while let Some(pre_start) = rest.find("<pre><code") {
        output.push_str(&rest[..pre_start]);
        let candidate = &rest[pre_start..];
        let Some(open_end) = candidate.find('>') else {
            output.push_str(candidate);
            return output;
        };
        let content_start = open_end + 1;
        let Some(close_start) = candidate[content_start..].find("</code></pre>") else {
            output.push_str(candidate);
            return output;
        };
        let close_start = content_start + close_start;
        let close_end = close_start + "</code></pre>".len();
        let open_tag = &candidate[..content_start];
        let code = &candidate[content_start..close_start];
        output.push_str(open_tag);
        output.push_str(&highlight_code_content(
            &decode_export_html_entities(code),
            code_language(open_tag),
        ));
        output.push_str("</code></pre>");
        rest = &candidate[close_end..];
    }
    output.push_str(rest);
    output
}

fn code_language(open_tag: &str) -> Option<&str> {
    let marker = "language-";
    let start = open_tag.find(marker)? + marker.len();
    let language = open_tag[start..]
        .split(|ch: char| !(ch.is_ascii_alphanumeric() || ch == '-' || ch == '_'))
        .next()
        .filter(|value| !value.is_empty())?;
    Some(language)
}

fn highlight_code_content(code: &str, language: Option<&str>) -> String {
    let mut output = String::with_capacity(code.len());
    let bytes = code.as_bytes();
    let mut index = 0usize;
    while index < bytes.len() {
        if is_comment_start(code, index, language) {
            let end = code[index..]
                .find('\n')
                .map(|offset| index + offset)
                .unwrap_or(code.len());
            push_span(&mut output, "syn-comment", &code[index..end]);
            index = end;
        } else if matches!(bytes[index], b'\'' | b'"') {
            let end = quoted_literal_end(code, index);
            push_span(&mut output, "syn-string", &code[index..end]);
            index = end;
        } else if bytes[index].is_ascii_digit() {
            let end = scan_while(code, index, |byte| {
                byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_')
            });
            push_span(&mut output, "syn-number", &code[index..end]);
            index = end;
        } else if bytes[index].is_ascii_alphabetic() || bytes[index] == b'_' {
            let end = scan_while(code, index, |byte| {
                byte.is_ascii_alphanumeric() || byte == b'_'
            });
            let token = &code[index..end];
            if is_keyword(token) {
                push_span(&mut output, "syn-keyword", token);
            } else {
                output.push_str(&escape_html(token));
            }
            index = end;
        } else {
            let ch = code[index..]
                .chars()
                .next()
                .expect("index should point at a char boundary");
            output.push_str(&escape_html(&ch.to_string()));
            index += ch.len_utf8();
        }
    }
    output
}

fn is_comment_start(code: &str, index: usize, language: Option<&str>) -> bool {
    let rest = &code[index..];
    if rest.starts_with("//") {
        return true;
    }
    if rest.starts_with('#') {
        return matches!(
            language,
            Some("py" | "python" | "sh" | "bash" | "zsh" | "yaml" | "yml" | "toml")
        );
    }
    false
}

fn quoted_literal_end(code: &str, start: usize) -> usize {
    let quote = code.as_bytes()[start];
    let mut index = start + 1;
    let bytes = code.as_bytes();
    while index < bytes.len() {
        if bytes[index] == b'\\' {
            index = (index + 2).min(bytes.len());
        } else if bytes[index] == quote {
            return index + 1;
        } else {
            index += 1;
        }
    }
    bytes.len()
}

fn scan_while(code: &str, start: usize, predicate: impl Fn(u8) -> bool) -> usize {
    let mut index = start;
    let bytes = code.as_bytes();
    while index < bytes.len() && predicate(bytes[index]) {
        index += 1;
    }
    index
}

fn is_keyword(token: &str) -> bool {
    matches!(
        token,
        "as" | "async"
            | "await"
            | "break"
            | "case"
            | "catch"
            | "class"
            | "const"
            | "continue"
            | "def"
            | "else"
            | "enum"
            | "export"
            | "false"
            | "fn"
            | "for"
            | "from"
            | "function"
            | "if"
            | "impl"
            | "import"
            | "in"
            | "let"
            | "match"
            | "mod"
            | "mut"
            | "return"
            | "self"
            | "struct"
            | "true"
            | "type"
            | "use"
            | "var"
            | "while"
    )
}

fn push_span(output: &mut String, class_name: &str, text: &str) {
    output.push_str("<span class=\"");
    output.push_str(class_name);
    output.push_str("\">");
    output.push_str(&escape_html(text));
    output.push_str("</span>");
}

fn html_appendix_sections(response: &CompileResponse, options: &Value) -> String {
    [
        html_glossary_section(response, options),
        html_comments_section(response, options),
        html_provenance_section(response, options),
        html_legal_disclaimer_section(response),
    ]
    .join("")
}

fn html_glossary_section(response: &CompileResponse, options: &Value) -> String {
    if !include_glossary(options) || response.semantic.glossary.is_empty() {
        return String::new();
    }
    let entries = response
        .semantic
        .glossary
        .iter()
        .map(|(term, definition)| {
            format!(
                "<dt>{}</dt><dd>{}</dd>",
                escape_html(term),
                escape_html(definition)
            )
        })
        .collect::<String>();
    format!("<section class=\"export-glossary\"><h2>Glossary</h2><dl>{entries}</dl></section>")
}

fn html_comments_section(response: &CompileResponse, options: &Value) -> String {
    if !include_comments(options)
        || (response.semantic.comments.is_empty() && response.semantic.change_notes.is_empty())
    {
        return String::new();
    }
    let entries = response
        .semantic
        .comments
        .iter()
        .map(|comment| {
            let created_at = empty_as(comment.created_at.as_str(), "undated");
            let author = empty_as(comment.author.as_str(), "local");
            format!(
                "<li><strong>Line {}</strong> <span>{}</span> <em>{} at {}</em><p>{}</p></li>",
                comment.line,
                escape_html(&comment.state),
                escape_html(author),
                escape_html(created_at),
                escape_html(&comment.text)
            )
        })
        .collect::<String>();
    let change_entries = response
        .semantic
        .change_notes
        .iter()
        .map(|note| {
            let created_at = empty_as(note.created_at.as_str(), "undated");
            let author = empty_as(note.author.as_str(), "local");
            format!(
                "<li><strong>Line {}</strong> <em>{} at {}</em><p>{}</p></li>",
                note.line,
                escape_html(author),
                escape_html(created_at),
                escape_html(&note.text)
            )
        })
        .collect::<String>();
    let changes = if change_entries.is_empty() {
        String::new()
    } else {
        format!("<h3>Change Notes</h3><ol>{change_entries}</ol>")
    };
    format!(
        "<section class=\"export-comments\"><h2>Review Comments</h2><ol>{entries}</ol>{changes}</section>"
    )
}

fn html_provenance_section(response: &CompileResponse, options: &Value) -> String {
    if !include_provenance(options)
        || (response.semantic.ai_sources.is_empty()
            && response.semantic.ai_assisted_sections.is_empty())
    {
        return String::new();
    }
    let source_entries = response
        .semantic
        .ai_sources
        .iter()
        .map(|source| {
            format!(
                "<li><strong>{}</strong> <span>{}</span><p>{}; reviewed by {} on {}; {}; prompt: {}</p></li>",
                escape_html(empty_as(source.provider.as_str(), "unknown provider")),
                escape_html(empty_as(source.model.as_str(), "unknown model")),
                escape_html(empty_as(source.date.as_str(), "undated")),
                escape_html(empty_as(source.reviewed_by.as_str(), "unreviewed")),
                escape_html(empty_as(source.reviewed_at.as_str(), "undated")),
                escape_html(&source.status),
                escape_html(empty_as(
                    source.prompt_summary.as_str(),
                    "no prompt summary"
                ))
            )
        })
        .collect::<String>();
    let section_entries = response
        .semantic
        .ai_assisted_sections
        .iter()
        .map(|section| {
            format!(
                "<li><strong>{}</strong> <span>line {}</span><p>{}; reviewed by {} on {}; source: {}; prompt: {}</p></li>",
                escape_html(&section.heading),
                section.line,
                escape_html(&section.status),
                escape_html(empty_as(section.reviewed_by.as_str(), "unreviewed")),
                escape_html(empty_as(section.reviewed_at.as_str(), "undated")),
                escape_html(empty_as(section.source.as_str(), "unspecified source")),
                escape_html(empty_as(section.prompt_summary.as_str(), "no prompt summary"))
            )
        })
        .collect::<String>();
    let entries = format!("{source_entries}{section_entries}");
    format!(
        "<section class=\"export-provenance\"><h2>AI Provenance</h2><ol>{entries}</ol></section>"
    )
}

fn html_legal_disclaimer_section(response: &CompileResponse) -> String {
    let Some(disclaimer) = metadata_string(&response.metadata, "legalDisclaimer")
        .filter(|value| !value.trim().is_empty())
    else {
        return String::new();
    };
    format!(
        "<section class=\"export-legal\"><h2>Legal Disclaimer</h2><p>{}</p></section>",
        escape_html(&disclaimer)
    )
}

fn export_css(
    brand_color: &str,
    watermark: &str,
    brand_font: &str,
    page_numbers: bool,
    layout_preset: &str,
    syntax_highlighting: bool,
    metadata: &Value,
) -> String {
    let page_counter_rule = if page_numbers {
        "@bottom-center{content:'Page ' counter(page) ' of ' counter(pages)}"
    } else {
        ""
    };
    let (body_margin, body_line_height, cover_min_height, heading_size, page_margin) =
        match layout_preset {
            "compact" => ("32px", "1.42", "72vh", "36px", "18mm"),
            "presentation" => ("64px", "1.7", "78vh", "54px", "20mm"),
            _ => ("48px", "1.55", "85vh", "44px", "24mm"),
        };
    let page_size_name = match layout_page_size(metadata).as_str() {
        "letter" => "Letter",
        "legal" => "Legal",
        _ => "A4",
    };
    let page_size = if layout_orientation(metadata) == "landscape" {
        format!("{page_size_name} landscape")
    } else {
        page_size_name.to_string()
    };
    let page_margin = match explicit_layout_margins(metadata).as_deref() {
        Some("narrow") | Some("compact") => "12mm",
        Some("wide") => "32mm",
        Some("normal") => "24mm",
        _ => page_margin,
    };
    let syntax_rules = if syntax_highlighting {
        ".syn-keyword{color:#7c3aed;font-weight:700}.syn-string{color:#047857}.syn-number{color:#b45309}.syn-comment{color:#64748b;font-style:italic}"
    } else {
        ""
    };
    let figure_position_rules = "figure[data-position='top'] img,.figure-position-top img{object-position:center top}figure[data-position='bottom'] img,.figure-position-bottom img{object-position:center bottom}figure[data-position='left'] img,.figure-position-left img{object-position:left center}figure[data-position='right'] img,.figure-position-right img{object-position:right center}figure[data-position='top-left'] img,.figure-position-top-left img{object-position:left top}figure[data-position='top-right'] img,.figure-position-top-right img{object-position:right top}figure[data-position='bottom-left'] img,.figure-position-bottom-left img{object-position:left bottom}figure[data-position='bottom-right'] img,.figure-position-bottom-right img{object-position:right bottom}";
    let math_rules = ".math-root-index{font-size:.65em;vertical-align:super}.math-text{font-family:inherit}.math-blackboard{font-family:Georgia,'Times New Roman',serif;font-weight:700}.math-calligraphic{font-family:'Snell Roundhand','Apple Chancery',cursive}.math-roman{font-family:Georgia,'Times New Roman',serif;font-style:normal}.math-hat::before,.math-vec::before{display:block;height:0;line-height:0;text-align:center}.math-hat::before{content:'^'}.math-vec::before{content:'→'}.math-overline{border-top:1px solid currentColor}.math-underline{border-bottom:1px solid currentColor}.math-align-separator{display:inline-block;min-width:1ch}.math-matrix{display:inline-flex;align-items:center;gap:4px;vertical-align:middle}.math-matrix::before,.math-matrix::after{font-size:1.8em;line-height:1}.math-matrix.matrix-round::before{content:'('}.math-matrix.matrix-round::after{content:')'}.math-matrix.matrix-square::before{content:'['}.math-matrix.matrix-square::after{content:']'}.math-matrix.matrix-vertical::before,.math-matrix.matrix-vertical::after{content:'|'}.math-matrix.matrix-cases::before{content:'{'}.math-matrix.matrix-cases::after{content:''}.math-matrix table{width:auto;border-collapse:collapse;display:inline-table}.math-matrix td{border:0;padding:0 .45ch;text-align:center}";
    let citation_popover_rules = ".citation{position:relative;cursor:help}.citation[data-citation-detail]:hover::after,.citation[data-citation-detail]:focus::after{content:attr(data-citation-detail);position:absolute;left:0;bottom:calc(100% + 6px);z-index:20;width:max-content;max-width:min(320px,80vw);white-space:normal;background:#111827;color:#fff;border:1px solid #374151;border-radius:4px;box-shadow:0 12px 24px rgba(15,23,42,.22);padding:8px 10px;font-size:.84rem;line-height:1.35;font-weight:500}";
    format!(
        "body{{font-family:{};margin:{body_margin};color:#1f2937;line-height:{body_line_height}}}.running-header{{position:running(header);border-bottom:3px solid {brand_color};padding-bottom:8px;color:#475569}}.cover{{min-height:{cover_min_height};display:flex;flex-direction:column;justify-content:center;border-left:10px solid {brand_color};padding-left:32px;page-break-after:always}}.cover-logo{{max-width:160px;max-height:80px;object-fit:contain;margin-bottom:24px}}.cover h1{{font-size:{heading_size};margin:0 0 12px}}.subtitle{{font-size:22px;color:#475569}}.status{{display:inline-block;color:{brand_color};font-weight:700;text-transform:uppercase}}footer{{display:flex;justify-content:space-between;gap:16px;margin-top:40px;border-top:1px solid #cbd5e1;padding-top:12px;color:#475569}}h1,h2,h3{{color:#111827}}p,li,blockquote{{orphans:2;widows:2}}table{{border-collapse:collapse;width:100%}}td,th{{border:1px solid #cbd5e1;padding:6px 8px}}figure[data-float='right'],.figure-float-right{{float:right;max-width:45%;margin:0 0 16px 24px}}figure[data-float='left'],.figure-float-left{{float:left;max-width:45%;margin:0 24px 16px 0}}figure[data-fit='cover'] img,.figure-fit-cover img{{width:100%;aspect-ratio:16/9;object-fit:cover}}{figure_position_rules}.citation{{color:{brand_color};font-weight:700}}{citation_popover_rules}.glossary-term{{border-bottom:1px dotted {brand_color};color:{brand_color};cursor:help}}.callout{{border-left:4px solid {brand_color};background:#eefaf4;padding:10px 12px;margin:14px 0}}.callout strong{{display:block;color:#0f5132;margin-bottom:4px}}.equation{{margin:18px 0}}.math-rendered{{font-family:Georgia,'Times New Roman',serif;font-size:1.08em}}.math-display{{padding:12px;border:1px solid #d8e0e8;background:#f8fafc;text-align:center}}.math-frac{{display:inline-grid;grid-template-rows:auto auto;vertical-align:middle;text-align:center}}.math-frac span:first-child{{border-bottom:1px solid currentColor}}.math-sqrt::before{{content:'√'}}{math_rules}.math-source-inline{{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0)}}.export-glossary,.export-comments,.export-provenance,.export-legal{{page-break-before:always;border-top:3px solid {brand_color};margin-top:40px;padding-top:16px}}.export-glossary dt{{font-weight:700;color:#111827}}.export-glossary dd{{margin:0 0 10px 0}}.export-comments li,.export-provenance li{{margin-bottom:12px}}.export-comments p,.export-provenance p{{margin:4px 0 0}}{syntax_rules}main::before{{content:'{}';position:fixed;inset:35% auto auto 20%;font-size:64px;color:rgba(0,0,0,.06);transform:rotate(-25deg);z-index:-1}}.page-break{{page-break-after:always}}@page{{size:{page_size};margin:{page_margin};@top-center{{content:element(header)}}{page_counter_rule}}}",
        escape_css(brand_font),
        escape_css(watermark)
    )
}
