use super::*;
use serde_json::Value;

pub(crate) fn render_latex_bytes(
    response: &CompileResponse,
    manifest: &ExportManifest,
) -> Result<Vec<u8>, String> {
    let template = latex_template_spec(&manifest.export_options);
    let mut output = String::new();
    output.push_str("% Generated by NEditor\n");
    output.push_str(&format!("% Source hash: {}\n", manifest.source_hash));
    output.push_str(&format!("% Export target: {}\n\n", manifest.export_target));
    output.push_str(&format!(
        "% LaTeX template: {} ({})\n",
        template.label, template.id
    ));
    output.push_str(&format!(
        "\\documentclass[{}]{{{}}}\n",
        template.class_options, template.document_class
    ));
    for package in &template.packages {
        output.push_str(package);
        output.push('\n');
    }
    output.push_str(&format!("\\geometry{{{}}}\n", template.geometry));
    output.push_str(&format!("\\hypersetup{{{}}}\n", template.hypersetup));
    if !template.header.trim().is_empty() {
        output.push_str(&template.header);
        output.push('\n');
    }
    output.push('\n');
    output.push_str(&format!(
        "\\title{{{}}}\n",
        latex_escape(&response.semantic.title)
    ));
    if let Some(author) = metadata_string(&response.metadata, "author")
        .or_else(|| metadata_string(&response.metadata, "approvedBy"))
    {
        output.push_str(&format!("\\author{{{}}}\n", latex_escape(&author)));
    }
    if let Some(date) = metadata_string(&response.metadata, "date")
        .or_else(|| metadata_string(&response.metadata, "approvedAt"))
    {
        output.push_str(&format!("\\date{{{}}}\n", latex_escape(&date)));
    }
    output.push_str("\\begin{document}\n\\maketitle\n\n");
    output.push_str(&render_latex_metadata(response, manifest));
    for block in &response.document_ast.blocks {
        output.push_str(&render_latex_block(block, &template));
    }
    output.push_str("\\end{document}\n");
    Ok(output.into_bytes())
}

struct LatexTemplateSpec {
    id: String,
    label: String,
    document_class: String,
    class_options: String,
    packages: Vec<String>,
    geometry: String,
    hypersetup: String,
    header: String,
    chapter_style: bool,
}

const BASE_LATEX_PACKAGES: &[&str] = &[
    "\\usepackage[utf8]{inputenc}",
    "\\usepackage[T1]{fontenc}",
    "\\usepackage{geometry}",
    "\\usepackage{hyperref}",
    "\\usepackage{longtable}",
    "\\usepackage{array}",
    "\\usepackage{graphicx}",
    "\\usepackage{enumitem}",
    "\\usepackage{amsmath}",
    "\\usepackage{amssymb}",
];

const BUSINESS_LATEX_PACKAGES: &[&str] = &[
    "\\usepackage[utf8]{inputenc}",
    "\\usepackage[T1]{fontenc}",
    "\\usepackage{geometry}",
    "\\usepackage{hyperref}",
    "\\usepackage{longtable}",
    "\\usepackage{array}",
    "\\usepackage{graphicx}",
    "\\usepackage{enumitem}",
    "\\usepackage{amsmath}",
    "\\usepackage{booktabs}",
    "\\usepackage{xcolor}",
    "\\usepackage{fancyhdr}",
    "\\usepackage{microtype}",
];

fn latex_template_spec(options: &Value) -> LatexTemplateSpec {
    if let Some(spec) = custom_latex_template_spec(options) {
        return spec;
    }
    match options.get("latexTemplate").and_then(Value::as_str) {
        Some("business-report") => LatexTemplateSpec {
            id: "business-report".to_string(),
            label: "Business Report".to_string(),
            document_class: "report".to_string(),
            class_options: "11pt".to_string(),
            packages: package_vec(BUSINESS_LATEX_PACKAGES),
            geometry: "margin=0.9in".to_string(),
            hypersetup: "colorlinks=true,linkcolor=blue,urlcolor=blue,pdftitle={NEditor Business Report}".to_string(),
            header: "\\pagestyle{fancy}\\fancyhf{}\\lhead{NEditor}\\rhead{Business Report}\\cfoot{\\thepage}".to_string(),
            chapter_style: true,
        },
        Some("proposal") => LatexTemplateSpec {
            id: "proposal".to_string(),
            label: "Proposal".to_string(),
            document_class: "article".to_string(),
            class_options: "11pt".to_string(),
            packages: package_vec(BUSINESS_LATEX_PACKAGES),
            geometry: "margin=0.85in".to_string(),
            hypersetup: "colorlinks=true,linkcolor=blue,urlcolor=blue,pdftitle={NEditor Proposal}".to_string(),
            header: "\\pagestyle{fancy}\\fancyhf{}\\lhead{Proposal}\\rhead{\\thepage}".to_string(),
            chapter_style: false,
        },
        Some("rfp-response") => LatexTemplateSpec {
            id: "rfp-response".to_string(),
            label: "RFP Response".to_string(),
            document_class: "article".to_string(),
            class_options: "11pt".to_string(),
            packages: package_vec(BUSINESS_LATEX_PACKAGES),
            geometry: "margin=0.8in".to_string(),
            hypersetup: "colorlinks=true,linkcolor=blue,urlcolor=blue,pdftitle={NEditor RFP Response}".to_string(),
            header: "\\pagestyle{fancy}\\fancyhf{}\\lhead{Compliance Response}\\rhead{\\thepage}".to_string(),
            chapter_style: false,
        },
        Some("technical-report") => LatexTemplateSpec {
            id: "technical-report".to_string(),
            label: "Technical Report".to_string(),
            document_class: "report".to_string(),
            class_options: "11pt".to_string(),
            packages: package_vec(BASE_LATEX_PACKAGES),
            geometry: "margin=1in".to_string(),
            hypersetup: "colorlinks=true,linkcolor=blue,urlcolor=blue,pdftitle={NEditor Technical Report}".to_string(),
            header: String::new(),
            chapter_style: true,
        },
        Some("academic-paper") => LatexTemplateSpec {
            id: "academic-paper".to_string(),
            label: "Academic Paper".to_string(),
            document_class: "article".to_string(),
            class_options: "11pt".to_string(),
            packages: package_vec(BASE_LATEX_PACKAGES),
            geometry: "margin=1in".to_string(),
            hypersetup: "colorlinks=true,linkcolor=blue,urlcolor=blue,pdftitle={NEditor Academic Paper}".to_string(),
            header: String::new(),
            chapter_style: false,
        },
        Some("textbook") => LatexTemplateSpec {
            id: "textbook".to_string(),
            label: "Textbook".to_string(),
            document_class: "book".to_string(),
            class_options: "11pt,oneside".to_string(),
            packages: package_vec(BASE_LATEX_PACKAGES),
            geometry: "margin=1in".to_string(),
            hypersetup: "colorlinks=true,linkcolor=blue,urlcolor=blue,pdftitle={NEditor Textbook}".to_string(),
            header: String::new(),
            chapter_style: true,
        },
        Some("book") => LatexTemplateSpec {
            id: "book".to_string(),
            label: "Book".to_string(),
            document_class: "book".to_string(),
            class_options: "11pt,oneside".to_string(),
            packages: package_vec(BASE_LATEX_PACKAGES),
            geometry: "margin=1in".to_string(),
            hypersetup: "colorlinks=true,linkcolor=blue,urlcolor=blue,pdftitle={NEditor Book}".to_string(),
            header: String::new(),
            chapter_style: true,
        },
        _ => LatexTemplateSpec {
            id: "article".to_string(),
            label: "Article".to_string(),
            document_class: "article".to_string(),
            class_options: "11pt".to_string(),
            packages: package_vec(BASE_LATEX_PACKAGES),
            geometry: "margin=1in".to_string(),
            hypersetup: "colorlinks=true,linkcolor=blue,urlcolor=blue".to_string(),
            header: String::new(),
            chapter_style: false,
        },
    }
}

fn package_vec(packages: &[&str]) -> Vec<String> {
    packages.iter().map(|package| package.to_string()).collect()
}

fn custom_latex_template_spec(options: &Value) -> Option<LatexTemplateSpec> {
    let profile = options.get("latexTemplateProfile")?.as_object()?;
    let id = profile.get("id")?.as_str()?.trim();
    let selected = options.get("latexTemplate").and_then(Value::as_str)?.trim();
    if id.is_empty() || id != selected {
        return None;
    }
    let document_class = profile
        .get("documentClass")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .unwrap_or("article");
    let packages = profile
        .get("packages")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(Value::as_str)
                .map(str::trim)
                .filter(|value| !value.is_empty())
                .take(24)
                .map(ToString::to_string)
                .collect::<Vec<_>>()
        })
        .filter(|items| !items.is_empty())
        .unwrap_or_else(|| package_vec(BASE_LATEX_PACKAGES));
    Some(LatexTemplateSpec {
        id: id.to_string(),
        label: profile
            .get("label")
            .and_then(Value::as_str)
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .unwrap_or("Custom LaTeX Template")
            .to_string(),
        document_class: document_class.to_string(),
        class_options: profile
            .get("classOptions")
            .and_then(Value::as_str)
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .unwrap_or("11pt")
            .to_string(),
        packages,
        geometry: profile
            .get("geometry")
            .and_then(Value::as_str)
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .unwrap_or("margin=1in")
            .to_string(),
        hypersetup: profile
            .get("hypersetup")
            .and_then(Value::as_str)
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .unwrap_or("colorlinks=true,linkcolor=blue,urlcolor=blue")
            .to_string(),
        header: profile
            .get("header")
            .and_then(Value::as_str)
            .unwrap_or("")
            .trim()
            .to_string(),
        chapter_style: profile
            .get("chapterStyle")
            .and_then(Value::as_bool)
            .unwrap_or(matches!(document_class, "book" | "report" | "memoir")),
    })
}

fn render_latex_metadata(response: &CompileResponse, manifest: &ExportManifest) -> String {
    let mut items = vec![
        ("Status", response.semantic.status.clone()),
        ("Source hash", manifest.source_hash.clone()),
    ];
    for (label, path) in [
        ("Version", "version"),
        ("Subtitle", "subtitle"),
        ("Client", "client"),
        ("Classification", "classification"),
        ("Approved by", "approvedBy"),
        ("Approved at", "approvedAt"),
    ] {
        if let Some(value) =
            metadata_string(&response.metadata, path).filter(|value| !value.trim().is_empty())
        {
            items.push((label, value));
        }
    }
    let entries = items
        .into_iter()
        .map(|(label, value)| {
            format!(
                "\\item[{}] {}\n",
                latex_escape(label),
                latex_escape(value.trim())
            )
        })
        .collect::<String>();
    format!(
        "\\section*{{Export Metadata}}\n\\begin{{description}}\n{entries}\\end{{description}}\n\n"
    )
}

fn render_latex_block(block: &DocumentBlock, template: &LatexTemplateSpec) -> String {
    match block {
        DocumentBlock::Heading { level, text, .. } => {
            format!(
                "{}{{{}}}\n\n",
                latex_heading_command(*level, template),
                latex_escape(text)
            )
        }
        DocumentBlock::Paragraph { text, inlines, .. } => {
            if inlines.is_empty() {
                format!("{}\n\n", latex_escape(text))
            } else {
                format!("{}\n\n", render_latex_inlines(inlines))
            }
        }
        DocumentBlock::List { ordered, items, .. } => {
            let environment = if *ordered { "enumerate" } else { "itemize" };
            let items = items
                .iter()
                .map(|item| format!("\\item {}\n", latex_inline_text(item)))
                .collect::<String>();
            format!("\\begin{{{environment}}}\n{items}\\end{{{environment}}}\n\n")
        }
        DocumentBlock::TaskList { items, .. } => {
            let items = items
                .iter()
                .map(|item| {
                    format!(
                        "\\item[{}] {}\n",
                        if item.checked { "[x]" } else { "[ ]" },
                        latex_inline_text(&item.text)
                    )
                })
                .collect::<String>();
            format!("\\begin{{itemize}}[leftmargin=*]\n{items}\\end{{itemize}}\n\n")
        }
        DocumentBlock::BlockQuote { text, .. } => {
            format!("\\begin{{quote}}\n{}\n\\end{{quote}}\n\n", latex_escape(text))
        }
        DocumentBlock::CodeBlock { language, code, .. } => {
            let label = language.as_deref().unwrap_or("text");
            format!(
                "% code block: {}\n{}\n",
                latex_escape(label),
                verbatim_safe(code)
            )
        }
        DocumentBlock::Table {
            id,
            caption,
            headers,
            rows,
            ..
        } => render_latex_table(id.as_deref(), caption.as_deref(), headers, rows),
        DocumentBlock::Figure {
            id,
            src,
            alt,
            caption,
            ..
        } => render_latex_figure(id.as_deref(), src.as_deref(), alt.as_deref(), caption.as_deref()),
        DocumentBlock::Equation {
            id,
            caption,
            text,
            ..
        } => {
            let mut output = String::new();
            if let Some(caption) = caption {
                output.push_str(&format!("% Equation: {}\n", latex_escape(caption)));
            }
            output.push_str("\\begin{equation}\n");
            output.push_str(text.trim());
            output.push('\n');
            if let Some(id) = id {
                output.push_str(&format!("\\label{{{}}}\n", latex_label(id)));
            }
            output.push_str("\\end{equation}\n\n");
            output
        }
        DocumentBlock::Layout {
            directive, options, ..
        } => format!(
            "% Layout directive omitted from LaTeX export: {} {}\n\n",
            latex_escape(directive),
            latex_escape(options)
        ),
        DocumentBlock::Callout {
            callout_type,
            title,
            text,
            ..
        } => format!(
            "\\begin{{quote}}\n\\textbf{{{}: {}}} {}\n\\end{{quote}}\n\n",
            latex_escape(callout_type),
            latex_escape(title),
            latex_escape(text)
        ),
        DocumentBlock::Footnotes { entries, .. } => {
            let entries = entries
                .iter()
                .map(|entry| {
                    format!(
                        "\\item[{}] {}\n",
                        latex_escape(&entry.key),
                        latex_inline_text(&entry.text)
                    )
                })
                .collect::<String>();
            format!("\\section*{{Footnotes}}\n\\begin{{description}}\n{entries}\\end{{description}}\n\n")
        }
        DocumentBlock::ReviewComment { comment, .. } => format!(
            "\\subsection*{{Review Comment}}\n\\textbf{{{}}} ({}, {}): {}\n\n",
            latex_escape(&comment.author),
            latex_escape(&comment.created_at),
            latex_escape(&comment.state),
            latex_escape(&comment.text)
        ),
        DocumentBlock::ChangeNote { note, .. } => format!(
            "\\subsection*{{Change Note}}\n\\textbf{{{}}} ({}): {}\n\n",
            latex_escape(&note.author),
            latex_escape(&note.created_at),
            latex_escape(&note.text)
        ),
        DocumentBlock::AiSource { provenance, .. } => format!(
            "\\subsection*{{AI Provenance}}\n{} {}: {}\n\n",
            latex_escape(&provenance.provider),
            latex_escape(&provenance.model),
            latex_escape(&provenance.prompt_summary)
        ),
        DocumentBlock::Transform {
            name,
            output_kind,
            text,
            ..
        } => format!(
            "\\subsection*{{Transform: {}}}\n\\textit{{{}}}\n{}\n",
            latex_escape(name),
            latex_escape(output_kind),
            verbatim_safe(text)
        ),
        DocumentBlock::RawHtml { html, .. } => format!(
            "% Raw HTML retained for audit only.\n{}\n",
            verbatim_safe(html)
        ),
    }
}

fn render_latex_table(
    id: Option<&str>,
    caption: Option<&str>,
    headers: &[String],
    rows: &[Vec<String>],
) -> String {
    if headers.is_empty() {
        return String::new();
    }
    let columns = format!("|{}|", vec!["l"; headers.len()].join("|"));
    let mut output = String::new();
    output.push_str(&format!("\\begin{{longtable}}{{{columns}}}\n\\hline\n"));
    if let Some(caption) = caption {
        output.push_str(&format!("\\caption{{{}}}", latex_escape(caption)));
        if let Some(id) = id {
            output.push_str(&format!("\\label{{{}}}", latex_label(id)));
        }
        output.push_str("\\\\\n\\hline\n");
    }
    output.push_str(&render_latex_table_row(headers));
    output.push_str("\\hline\n");
    for row in rows {
        output.push_str(&render_latex_table_row(row));
    }
    output.push_str("\\hline\n\\end{longtable}\n\n");
    output
}

fn render_latex_table_row(cells: &[String]) -> String {
    format!(
        "{} \\\\\n",
        cells
            .iter()
            .map(|cell| latex_inline_text(cell))
            .collect::<Vec<_>>()
            .join(" & ")
    )
}

fn render_latex_figure(
    id: Option<&str>,
    src: Option<&str>,
    alt: Option<&str>,
    caption: Option<&str>,
) -> String {
    let caption = caption.or(alt).unwrap_or("Figure");
    let source = src.unwrap_or("");
    let mut output = String::new();
    output.push_str("\\begin{figure}[h]\n\\centering\n");
    let use_fbox = source.starts_with("data:")
        || source.trim().is_empty()
        || !source.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-' | '/'));
    if use_fbox {
        output.push_str(&format!(
            "\\fbox{{\\parbox{{0.85\\linewidth}}{{{}}}}}\n",
            latex_escape(alt.unwrap_or("Embedded image"))
        ));
    } else {
        output.push_str(&format!(
            "\\includegraphics[width=0.85\\linewidth]{{{source}}}\n"
        ));
    }
    output.push_str(&format!("\\caption{{{}}}\n", latex_escape(caption)));
    if let Some(id) = id {
        output.push_str(&format!("\\label{{{}}}\n", latex_label(id)));
    }
    output.push_str("\\end{figure}\n\n");
    output
}

fn latex_heading_command(level: usize, template: &LatexTemplateSpec) -> &'static str {
    if template.chapter_style {
        return match level {
            1 => "\\chapter",
            2 => "\\section",
            3 => "\\subsection",
            4 => "\\subsubsection",
            5 => "\\paragraph",
            _ => "\\subparagraph",
        };
    }
    match level {
        1 => "\\section",
        2 => "\\subsection",
        3 => "\\subsubsection",
        4 => "\\paragraph",
        _ => "\\subparagraph",
    }
}

fn render_latex_inlines(inlines: &[InlineNode]) -> String {
    inlines
        .iter()
        .map(|inline| match inline {
            InlineNode::Text { text } => latex_escape(text),
            InlineNode::Strong { text } => format!("\\textbf{{{}}}", latex_escape(text)),
            InlineNode::Emphasis { text } => format!("\\emph{{{}}}", latex_escape(text)),
            InlineNode::Code { text } => format!("\\texttt{{{}}}", latex_escape(text)),
            InlineNode::Link { text, url } => render_latex_link(text, url),
            InlineNode::Citation { raw, .. } => latex_escape(raw),
            InlineNode::CrossReference { key, .. } => format!("\\ref{{{}}}", latex_label(key)),
            InlineNode::FootnoteReference { key, .. } => {
                format!("\\footnote{{{}}}", latex_escape(key))
            }
        })
        .collect::<String>()
}

fn render_latex_link(text: &str, url: &str) -> String {
    if let Some(anchor) = url.strip_prefix('#').filter(|anchor| !anchor.is_empty()) {
        return format!(
            "\\hyperref[{}]{{{}}}",
            latex_label(anchor),
            latex_escape(text)
        );
    }
    format!("\\href{{{}}}{{{}}}", latex_escape(url), latex_escape(text))
}

fn latex_inline_text(text: &str) -> String {
    latex_escape(text)
}

fn latex_label(value: &str) -> String {
    value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || matches!(ch, ':' | '-' | '_') {
                ch
            } else {
                '-'
            }
        })
        .collect::<String>()
}

/// Wrap `content` in one or more verbatim blocks such that any literal
/// `\end{verbatim}` inside the content cannot prematurely close the environment.
/// Each occurrence is split out and rendered as an inline `\texttt` snippet
/// between two verbatim blocks, which is the only LaTeX-safe approach since
/// backslash has no special meaning inside a verbatim environment.
fn verbatim_safe(content: &str) -> String {
    const TAG: &str = "\\end{verbatim}";
    let segments: Vec<&str> = content.split(TAG).collect();
    if segments.len() == 1 {
        return format!("\\begin{{verbatim}}\n{content}\n\\end{{verbatim}}");
    }
    let mut out = String::new();
    for (i, seg) in segments.iter().enumerate() {
        out.push_str("\\begin{verbatim}\n");
        out.push_str(seg);
        out.push_str("\n\\end{verbatim}");
        if i + 1 < segments.len() {
            // Render the literal \end{verbatim} text safely outside verbatim.
            out.push_str("\\texttt{\\textbackslash end\\{verbatim\\}}");
        }
    }
    out
}

fn latex_escape(value: impl AsRef<str>) -> String {
    let mut escaped = String::new();
    for ch in value.as_ref().chars() {
        match ch {
            '\\' => escaped.push_str("\\textbackslash{}"),
            '{' => escaped.push_str("\\{"),
            '}' => escaped.push_str("\\}"),
            '$' => escaped.push_str("\\$"),
            '&' => escaped.push_str("\\&"),
            '%' => escaped.push_str("\\%"),
            '#' => escaped.push_str("\\#"),
            '_' => escaped.push_str("\\_"),
            '^' => escaped.push_str("\\textasciicircum{}"),
            '~' => escaped.push_str("\\textasciitilde{}"),
            _ => escaped.push(ch),
        }
    }
    escaped
}
