use super::*;

pub(crate) fn render_latex_bytes(
    response: &CompileResponse,
    manifest: &ExportManifest,
) -> Result<Vec<u8>, String> {
    let mut output = String::new();
    output.push_str("% Generated by NEditor\n");
    output.push_str(&format!("% Source hash: {}\n", manifest.source_hash));
    output.push_str(&format!("% Export target: {}\n\n", manifest.export_target));
    output.push_str("\\documentclass[11pt]{article}\n");
    output.push_str("\\usepackage[utf8]{inputenc}\n");
    output.push_str("\\usepackage[T1]{fontenc}\n");
    output.push_str("\\usepackage{geometry}\n");
    output.push_str("\\usepackage{hyperref}\n");
    output.push_str("\\usepackage{longtable}\n");
    output.push_str("\\usepackage{array}\n");
    output.push_str("\\usepackage{graphicx}\n");
    output.push_str("\\usepackage{enumitem}\n");
    output.push_str("\\geometry{margin=1in}\n");
    output.push_str("\\hypersetup{colorlinks=true,linkcolor=blue,urlcolor=blue}\n\n");
    output.push_str(&format!(
        "\\title{{{}}}\n",
        latex_escape(&response.semantic.title)
    ));
    if let Some(author) = metadata_string(&response.metadata, "author")
        .or_else(|| metadata_string(&response.metadata, "approvedBy"))
    {
        output.push_str(&format!("\\author{{{}}}\n", latex_escape(&author)));
    }
    if let Some(date) = metadata_string(&response.metadata, "date")
        .or_else(|| metadata_string(&response.metadata, "approvedAt"))
    {
        output.push_str(&format!("\\date{{{}}}\n", latex_escape(&date)));
    }
    output.push_str("\\begin{document}\n\\maketitle\n\n");
    output.push_str(&render_latex_metadata(response, manifest));
    for block in &response.document_ast.blocks {
        output.push_str(&render_latex_block(block));
    }
    output.push_str("\\end{document}\n");
    Ok(output.into_bytes())
}

fn render_latex_metadata(response: &CompileResponse, manifest: &ExportManifest) -> String {
    let mut items = vec![
        ("Status", response.semantic.status.clone()),
        ("Source hash", manifest.source_hash.clone()),
    ];
    for (label, path) in [
        ("Version", "version"),
        ("Subtitle", "subtitle"),
        ("Client", "client"),
        ("Classification", "classification"),
        ("Approved by", "approvedBy"),
        ("Approved at", "approvedAt"),
    ] {
        if let Some(value) =
            metadata_string(&response.metadata, path).filter(|value| !value.trim().is_empty())
        {
            items.push((label, value));
        }
    }
    let entries = items
        .into_iter()
        .map(|(label, value)| {
            format!(
                "\\item[{}] {}\n",
                latex_escape(label),
                latex_escape(value.trim())
            )
        })
        .collect::<String>();
    format!(
        "\\section*{{Export Metadata}}\n\\begin{{description}}\n{entries}\\end{{description}}\n\n"
    )
}

fn render_latex_block(block: &DocumentBlock) -> String {
    match block {
        DocumentBlock::Heading { level, text, .. } => {
            format!("{}{{{}}}\n\n", latex_heading_command(*level), latex_escape(text))
        }
        DocumentBlock::Paragraph { text, inlines, .. } => {
            if inlines.is_empty() {
                format!("{}\n\n", latex_escape(text))
            } else {
                format!("{}\n\n", render_latex_inlines(inlines))
            }
        }
        DocumentBlock::List { ordered, items, .. } => {
            let environment = if *ordered { "enumerate" } else { "itemize" };
            let items = items
                .iter()
                .map(|item| format!("\\item {}\n", latex_inline_text(item)))
                .collect::<String>();
            format!("\\begin{{{environment}}}\n{items}\\end{{{environment}}}\n\n")
        }
        DocumentBlock::TaskList { items, .. } => {
            let items = items
                .iter()
                .map(|item| {
                    format!(
                        "\\item[{}] {}\n",
                        if item.checked { "[x]" } else { "[ ]" },
                        latex_inline_text(&item.text)
                    )
                })
                .collect::<String>();
            format!("\\begin{{itemize}}[leftmargin=*]\n{items}\\end{{itemize}}\n\n")
        }
        DocumentBlock::BlockQuote { text, .. } => {
            format!("\\begin{{quote}}\n{}\n\\end{{quote}}\n\n", latex_escape(text))
        }
        DocumentBlock::CodeBlock { language, code, .. } => {
            let label = language.as_deref().unwrap_or("text");
            format!(
                "% code block: {}\n\\begin{{verbatim}}\n{}\n\\end{{verbatim}}\n\n",
                latex_escape(label),
                code.replace("\\end{verbatim}", "\\end\\{verbatim\\}")
            )
        }
        DocumentBlock::Table {
            id,
            caption,
            headers,
            rows,
            ..
        } => render_latex_table(id.as_deref(), caption.as_deref(), headers, rows),
        DocumentBlock::Figure {
            id,
            src,
            alt,
            caption,
            ..
        } => render_latex_figure(id.as_deref(), src.as_deref(), alt.as_deref(), caption.as_deref()),
        DocumentBlock::Equation {
            id,
            caption,
            text,
            ..
        } => {
            let mut output = String::new();
            if let Some(caption) = caption {
                output.push_str(&format!("% Equation: {}\n", latex_escape(caption)));
            }
            output.push_str("\\begin{equation}\n");
            output.push_str(text.trim());
            output.push('\n');
            if let Some(id) = id {
                output.push_str(&format!("\\label{{{}}}\n", latex_label(id)));
            }
            output.push_str("\\end{equation}\n\n");
            output
        }
        DocumentBlock::Layout {
            directive, options, ..
        } => format!(
            "% Layout directive omitted from LaTeX export: {} {}\n\n",
            latex_escape(directive),
            latex_escape(options)
        ),
        DocumentBlock::Callout {
            callout_type,
            title,
            text,
            ..
        } => format!(
            "\\begin{{quote}}\n\\textbf{{{}: {}}} {}\n\\end{{quote}}\n\n",
            latex_escape(callout_type),
            latex_escape(title),
            latex_escape(text)
        ),
        DocumentBlock::Footnotes { entries, .. } => {
            let entries = entries
                .iter()
                .map(|entry| {
                    format!(
                        "\\item[{}] {}\n",
                        latex_escape(&entry.key),
                        latex_inline_text(&entry.text)
                    )
                })
                .collect::<String>();
            format!("\\section*{{Footnotes}}\n\\begin{{description}}\n{entries}\\end{{description}}\n\n")
        }
        DocumentBlock::ReviewComment { comment, .. } => format!(
            "\\subsection*{{Review Comment}}\n\\textbf{{{}}} ({}, {}): {}\n\n",
            latex_escape(&comment.author),
            latex_escape(&comment.created_at),
            latex_escape(&comment.state),
            latex_escape(&comment.text)
        ),
        DocumentBlock::ChangeNote { note, .. } => format!(
            "\\subsection*{{Change Note}}\n\\textbf{{{}}} ({}): {}\n\n",
            latex_escape(&note.author),
            latex_escape(&note.created_at),
            latex_escape(&note.text)
        ),
        DocumentBlock::AiSource { provenance, .. } => format!(
            "\\subsection*{{AI Provenance}}\n{} {}: {}\n\n",
            latex_escape(&provenance.provider),
            latex_escape(&provenance.model),
            latex_escape(&provenance.prompt_summary)
        ),
        DocumentBlock::Transform {
            name,
            output_kind,
            text,
            ..
        } => format!(
            "\\subsection*{{Transform: {}}}\n\\textit{{{}}}\n\\begin{{verbatim}}\n{}\n\\end{{verbatim}}\n\n",
            latex_escape(name),
            latex_escape(output_kind),
            text.replace("\\end{verbatim}", "\\end\\{verbatim\\}")
        ),
        DocumentBlock::RawHtml { html, .. } => format!(
            "% Raw HTML retained for audit only.\n\\begin{{verbatim}}\n{}\n\\end{{verbatim}}\n\n",
            html.replace("\\end{verbatim}", "\\end\\{verbatim\\}")
        ),
    }
}

fn render_latex_table(
    id: Option<&str>,
    caption: Option<&str>,
    headers: &[String],
    rows: &[Vec<String>],
) -> String {
    if headers.is_empty() {
        return String::new();
    }
    let columns = format!("|{}|", vec!["l"; headers.len()].join("|"));
    let mut output = String::new();
    output.push_str(&format!("\\begin{{longtable}}{{{columns}}}\n\\hline\n"));
    if let Some(caption) = caption {
        output.push_str(&format!("\\caption{{{}}}", latex_escape(caption)));
        if let Some(id) = id {
            output.push_str(&format!("\\label{{{}}}", latex_label(id)));
        }
        output.push_str("\\\\\n\\hline\n");
    }
    output.push_str(&render_latex_table_row(headers));
    output.push_str("\\hline\n");
    for row in rows {
        output.push_str(&render_latex_table_row(row));
    }
    output.push_str("\\hline\n\\end{longtable}\n\n");
    output
}

fn render_latex_table_row(cells: &[String]) -> String {
    format!(
        "{} \\\\\n",
        cells
            .iter()
            .map(|cell| latex_inline_text(cell))
            .collect::<Vec<_>>()
            .join(" & ")
    )
}

fn render_latex_figure(
    id: Option<&str>,
    src: Option<&str>,
    alt: Option<&str>,
    caption: Option<&str>,
) -> String {
    let caption = caption.or(alt).unwrap_or("Figure");
    let source = src.unwrap_or("");
    let mut output = String::new();
    output.push_str("\\begin{figure}[h]\n\\centering\n");
    if source.starts_with("data:") || source.trim().is_empty() {
        output.push_str(&format!(
            "\\fbox{{\\parbox{{0.85\\linewidth}}{{{}}}}}\n",
            latex_escape(alt.unwrap_or("Embedded image"))
        ));
    } else {
        output.push_str(&format!(
            "\\includegraphics[width=0.85\\linewidth]{{{}}}\n",
            latex_escape(source)
        ));
    }
    output.push_str(&format!("\\caption{{{}}}\n", latex_escape(caption)));
    if let Some(id) = id {
        output.push_str(&format!("\\label{{{}}}\n", latex_label(id)));
    }
    output.push_str("\\end{figure}\n\n");
    output
}

fn latex_heading_command(level: usize) -> &'static str {
    match level {
        1 => "\\section",
        2 => "\\subsection",
        3 => "\\subsubsection",
        4 => "\\paragraph",
        _ => "\\subparagraph",
    }
}

fn render_latex_inlines(inlines: &[InlineNode]) -> String {
    inlines
        .iter()
        .map(|inline| match inline {
            InlineNode::Text { text } => latex_escape(text),
            InlineNode::Strong { text } => format!("\\textbf{{{}}}", latex_escape(text)),
            InlineNode::Emphasis { text } => format!("\\emph{{{}}}", latex_escape(text)),
            InlineNode::Code { text } => format!("\\texttt{{{}}}", latex_escape(text)),
            InlineNode::Link { text, url } => {
                format!("\\href{{{}}}{{{}}}", latex_escape(url), latex_escape(text))
            }
            InlineNode::Citation { raw, .. } => latex_escape(raw),
            InlineNode::CrossReference { key, .. } => format!("\\ref{{{}}}", latex_label(key)),
            InlineNode::FootnoteReference { key, .. } => {
                format!("\\footnote{{{}}}", latex_escape(key))
            }
        })
        .collect::<String>()
}

fn latex_inline_text(text: &str) -> String {
    latex_escape(text)
}

fn latex_label(value: &str) -> String {
    value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || matches!(ch, ':' | '-' | '_') {
                ch
            } else {
                '-'
            }
        })
        .collect::<String>()
}

fn latex_escape(value: impl AsRef<str>) -> String {
    let mut escaped = String::new();
    for ch in value.as_ref().chars() {
        match ch {
            '\\' => escaped.push_str("\\textbackslash{}"),
            '{' => escaped.push_str("\\{"),
            '}' => escaped.push_str("\\}"),
            '$' => escaped.push_str("\\$"),
            '&' => escaped.push_str("\\&"),
            '%' => escaped.push_str("\\%"),
            '#' => escaped.push_str("\\#"),
            '_' => escaped.push_str("\\_"),
            '^' => escaped.push_str("\\textasciicircum{}"),
            '~' => escaped.push_str("\\textasciitilde{}"),
            _ => escaped.push(ch),
        }
    }
    escaped
}
